### ISSUE TITLE
Login Failed[1]

### ISSUE THREAD

**Issue by alexcstark** [mintapi/mintapi#114]
I continually fail to receive a token from the following step:
https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L161

in printing the response that I get back, I have the following:

```
'{"CSRFToken":"","clientBuildNumber":"spa20170906.10","nickname":"","isCreditScoreRegistered":false,"error":{"vError":{"code":2,"isGlobalUser":null,"validatorProperty":null,"name":null,"copy":"That doesn\'t look like your Mint user ID. Try al******rk@g****.**m","type":"form"}},"showMigratePasswordPage":false,"buildNumber":"ph7788.3","supportedLocations":"\\/(login|ftuwelcome|welcome|overview|transaction|bills|planning|goal|trend|creditreport|save|oiiMigration|accountsetup|addprovider|settings|paystub|minttotax|taxcreditscore|taxw2s|minttotaxbrandshake|studentloan|consent).event"}'
```
The key error, to me, seems to be: `copy":"That doesn\'t look like your Mint user ID. Try al******rk@g****.**m","type":"form"}},`

It does not like my user id. However, on line 161, I don't see anywhere where we provide specific information about the specific user associated with the `loginUserSubmit` event. Is this all done from the cookies? What information is missing?

**Comment by jprouty** [comment]
@alexcstark can you please try again and report back? I just changed how requests are done and the auth model in #120

**Comment by mrooney** [comment]
I'm going to close this out as I haven't heard of this issue recently, but please let me know if you can still reproduce it with the latest version.
