### ISSUE TITLE
Login fails with clean install with python3 and pipenv

### ISSUE THREAD

**Issue by felciano** [mintapi/mintapi#122]
To try to shed some light on the authentication challenges I've done a clean install using python3 (per @jprouty's recommendation) and pipenv on OSX 10.12.6. 

```
brew install chromedriver
pipenv --three
pipenv install mintapi
pipenv install selenium
pipenv install keyring
pipenv install pandas
```
This still produces a login error:
```
pipenv run mintapi --keyring $USERNAME --accounts
Traceback (most recent call last):
  File "/Users/path/to/.Virtualenvs/clean-mint-kL-fqWz6/bin/mintapi", line 11, in <module>
    sys.exit(main())
  File "/Users/path/to/.Virtualenvs/clean-mint-kL-fqWz6/lib/python3.5/site-packages/mintapi/api.py", line 720, in main
    mint = Mint.create(email, password, ius_session=options.session, thx_guid=options.thx_guid)
  File "/Users/path/to/.Virtualenvs/clean-mint-kL-fqWz6/lib/python3.5/site-packages/mintapi/api.py", line 74, in create
    mint.login_and_get_token(email, password, ius_session, thx_guid)
  File "/Users/path/to/.Virtualenvs/clean-mint-kL-fqWz6/lib/python3.5/site-packages/mintapi/api.py", line 165, in login_and_get_token
    raise MintException('Mint.com login failed[1]')
mintapi.api.MintException: Mint.com login failed[1]
```

Visually, I can observe the chrome window brought up, and the correct username and password being typed in. However after that login form is submitted, the browser seems to redirect to `http://accounts.intuit.com/index.html` and briefly show the login form again.

Is this the same behavior selenium + chrome behavior that is observed when the process succeeds?

**Comment by jprouty** [comment]
Hey @felciano, I appreciate the continued efforts! I think I'll be trying the approach outlined in https://github.com/mrooney/mintapi/issues/122. Stay tuned!

**Comment by chuymax** [comment]
I can confirm issue on Ubuntu 17.10. Browser briefly shows the login form again as described by original poster.

**Comment by chuymax** [comment]
Windows version seems to behave ok (Win 10).

**Comment by alexsergeypetrov** [comment]
Also running into this on Ubuntu 16.04 :(

**Comment by jprouty** [comment]
@felciano Is this safe to close now that #120 is in?

**Comment by jlaw9** [comment]
@jprouty that pull request fixed the issue for me. Thanks! Unfortunately, now I'm getting a different error:

```
Traceback (most recent call last):
  File "manage-transactions.py", line 34, in <module>
    mint.get_accounts(True)
  File "/home/jeffl/.local/lib/python2.7/site-packages/mintapi/api.py", line 236, in get_accounts
    accounts = self.populate_extended_account_detail(accounts)
  File "/home/jeffl/.local/lib/python2.7/site-packages/mintapi/api.py", line 440, in populate_extended_account_detail
    account['availableMoney'] = Mint.parse_float(xml[1]['#text'])
AttributeError: class Mint has no attribute 'parse_float'
```
but I was able to fix that with the changes in this pull request: https://github.com/mrooney/mintapi/pull/133/commits/b790a36ebd92eae70ee4f2fd2e70f8983e73389e

**Comment by mrooney** [comment]
I'm going to close this out as I haven't heard of this issue recently, but please let me know if you can still reproduce it with the latest version.
