### ISSUE TITLE
Currency is always USD for all accounts

### ISSUE THREAD

**Issue by thumble** [mintapi/mintapi#125]
Hi, great work, I downloaded the API ran and all my accounts show the currency as USD, I know I have most in CAD. Can you please check.

**Comment by onlyrida** [comment]
Mint displays your transactions in the same amount as the bank account's/card's website shows but Mint has no way of identifying what currency it is and thus Mint always displays USD by default.

I suggest filing a feature request ticket to Mint.

**Comment by jaron-l** [comment]
I can't find any reference to mintapi claiming a currency. Perhaps this is with an old version? When running `mint.get_transactions()`, the return dataframe has no reference to a currency type. It just has the raw amount. Let me know if I am missing something else I'll close this.
