### ISSUE TITLE
Hanging on mintapi.Mint() - Using mintapi on Azure Functions

### ISSUE THREAD

**Issue by baumshl** [mintapi/mintapi#127]
Hi, 

I'm trying to use mintAPI within Azure Functions, and its hanging on the instantiation call, here's how my script looks like:

import os
import json
import sys, os.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname( __file__ ), 'myvenv/Lib/site-packages')))
import mintapi
mint = mintapi.Mint(email = "myemailhere", password = "passhere", ius_session = "sessionHere", thx_guid = "thxguidHere")

The reason I'm pointing out its on Azure functions is because its known not to support selenium/chromedriver, hence I had to populate the session and guid values manually. 

Here's a SO post that outlines how I've setup the environment (see note from Laurent Mazuel [here](https://stackoverflow.com/questions/43970307/azure-functions-installing-python-modules-and-extensions-on-consumption-plan) on detailed setup steps). 

Thanks for your help!

**Comment by mrooney** [comment]
Thanks! At this point, due to the complexity of Intuit's web app,
chromedriver is the only functional solution and the new default. If you
are able to find instructions that work, I'll happily update docs, but it
doesn't seem like a completely headless (except with xvfb) solution is
something I can maintain

**Comment by jaron-l** [comment]
Closing due to won't fix comment. As a side note, you could always integrate mintapi inside the selenium docker container, which is what I do. If I understand it correctly, this should work with Azure Functions.
