### ISSUE TITLE
"Session has expired" error

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#129]
When I do:
```
$ mintapi --keyring xxxx@xxxx.com --net-worth
```
A Chrome instance pops up and logs in to Mint -- every single time. It doesn't 'remember' any session info.

Then:
```
Traceback (most recent call last):
  File "/usr/local/bin/mintapi", line 9, in <module>
    load_entry_point('mintapi==1.28', 'console_scripts', 'mintapi')()
  File "/Library/Python/2.7/site-packages/mintapi/api.py", line 758, in main
    data = mint.get_net_worth()
  File "/Library/Python/2.7/site-packages/mintapi/api.py", line 412, in get_net_worth
    account_data = self.get_accounts()
  File "/Library/Python/2.7/site-packages/mintapi/api.py", line 248, in get_accounts
    raise MintException('Could not parse account data: ' + response)
mintapi.api.MintException: Could not parse account data: <error><code>1</code><description>Session has expired.</description><name></name><type></type></error>

```

From **python** it works ... but how do I avoid having to do the whole selenium login every time if I'm running a script periodically?

I tried:
```
pickle.dump( mint, open( "mint.p", "wb" ) )
mint = pickle.load( open( "mint.p", "rb" ) )
```
between sessions but then I get the same `Session has expired` error.

**UPDATE:** After further testing ... regardless of whether from shell, or python, or python3 ... and regardless of picking the mint object ... or just running the script with a delay ... or re-logging in with selenium ... after 1 or 2 calls I get this error. 

FWIW, `mint.initiate_account_refresh()` does not throw an error, ever. But any request for data does.

**Comment by dzg** [comment]
Maybe this has something to do with the "Invisible reCAPTCHA by Google"?

It _feels_ like it works when I log in manually...

**Comment by dzg** [comment]
I also noticed that when the selenium Chrome instance launches, it signs in correctly, but then opens the login page AGAIN, then quits. It never goes to the Mint Overview page or anything that looks like it's really logged in.

**Comment by prestonpope192** [comment]
Mine was doing the same thing described in the last comment above before I reinstalled it. Now it never successfully finds the new correct intuit login screen.

**Comment by dzg** [comment]
After some more digging ... I found that the `api.py` from source is different than the version installed by pip.

If I run that one from python then it works -- except that it still launches a Chrome instance every time. No caching of session/token.

**Comment by prestonpope192** [comment]
Hmm, when I try to run the api.py from source here, it can't find "seleniumrequests".

Yet now my pip installed api.py runs when I run it alone and manually enter the password and username, however it briefly displays a screen with a recaptcha "I am not a robot" button then disappears, and returns null

**Comment by dzg** [comment]
@prestonpope192 – to use seleniumrequests you have to `pip install selenium-requests` ... silly hyphen.

**Comment by mrooney** [comment]
This should be resolved at this point, but please let me know if not :)
