### ISSUE TITLE
Does current version support scraping of 'bills' page?

### ISSUE THREAD

**Issue by rushingJustice** [mintapi/mintapi#134]
I see other pages, like 'transactions' and 'budget', but nothing that relates to 'bills'. Am I overlooking a method that contains this information, or does it not yet exist?

Basically, I am just looking for JSON data that contain:

- Name of Bill
- Amount
- Date Due
- Paid/Not Paid

Great work on this API, it's nice!

Mike

**Comment by mrooney** [comment]
I don't think so but I'm happy to take a PR!

**Comment by Dirt-Nasty** [comment]
I second this @mrooney !  Would be a great to pull that outside of Mint to visualize when future bills are due!

**Comment by jaron-l** [comment]
This has since been implemented.
