### ISSUE TITLE
Log in successful -- not able to retrieve any information after that

### ISSUE THREAD

**Issue by wipika** [mintapi/mintapi#139]
I managed to log in successfully using the command-line interface **(mintapi _username password_ _arguments_)** but it fails to do pretty much anything after that, no matter which argument I use.

Specifically:

--accounts give me a _"null"_ return

--budgets gives me a _"null"_ return

--net-worth gives me a "AttributeError: _'WebDriver' object has no attribute 'request'"_ error

Hopefully it's an easy fix - any help is much appreciated.

**Comment by jaron-l** [comment]
You should include your arguments in the same command as each command creates a new instance of the process. If you need separate commands, be sure to include a session path to speed up the login workflow (and include the login info for all subsequent commands). Let us know if this problem persists after this explanation.
