### ISSUE TITLE
unable to cache TLDs error 13

### ISSUE THREAD

**Issue by eljfe** [mintapi/mintapi#161]
Hi,
Just playing arond with this API - thanks for making it!  I haven't been able to get my dataframe yet tho.  The login goes smoothly then I wait, then I get this error:

unable to cache TLDs in file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tldextract/.tld_set'

Love some help with this bad boy when you all have some time...  

Many Thanks,

**Comment by jaron-l** [comment]
mintapi no longer relies on that package. Feel free to open another issue if you continue to have other problems.
