### ISSUE TITLE
Manual logins failing

### ISSUE THREAD

**Issue by jorythompson** [mintapi/mintapi#162]
Is anyone else having an issue logging into Mint by hand?
I am having an issue where, when I even login manually, I get the error: "Hmm.  That didn't work.  Lets get you back into your account" or "Uh-oh. Something went wrong.  Refreshing may solve the issue.".  If I try to login again, SOMETIMES it works.

Note that this is not a MintAPI-specific issue, I am poling for others in the same boat.

**Comment by jeffklassen** [comment]
Bump - this is happening for me as well using this library. I can log in normally with my password.

**Comment by jorythompson** [comment]
Anyone?  I've had to modify my code to repeatedly try to login until it succeeds!

**Comment by sam1010k** [comment]
I am running into the same issue, how have you gotten around it?

**Comment by jaron-l** [comment]
This might have something to do with cookies. Clearing your session path and trying again may help. Since this is old and doesn't directly have to do with a bug in mintapi, I'm going to close this. Feel free to reopen or create another issue if you continue to have problems.
