### ISSUE TITLE
Post transactions from a csv

### ISSUE THREAD

**Issue by tpinet** [mintapi/mintapi#164]
Mint does not allow for importing bulk transactions from a csv (https://www.quora.com/Why-doesnt-mint-com-allow-csv-import) and some banks are starting to block aggregators. For example I have a Canadian President's Choice (PC) MasterCard and in Nov 2018 they started blocking Mint. If I can export a CSV from the PC site and have a means to bulk import it would be great. 

Intuit used to have an API but it shut down in 2016 however Finicity picked up the torch to continue providing support for many other aggregator sites: 
- https://www.finicity.com/data-aggregators-unaffected-by-intuits-plan-to-close-its-financial-data-api-service/
- https://www.coveros.com/finicity-api-review/
- https://community.finicity.com/s/topic/0TO36000000HKHBGA4/finicity-aggregation-api?tabset-7e7a9=2

Some folks have done similar imports doing a scrape while adding a transaction to figure out the json req/resp:
- https://votecharlie.com/blog/2017/06/mint-batch-transaction-import-hack.html
- https://www.codeproject.com/Articles/1183561/%2FArticles%2F1183561%2FImporting-transactions-into-Mint-com-using-Csharp
- http://aaronfrancis.com/2013/importing-transactions-into-mint/

Thanks!

**Comment by eljfe** [comment]
LOL - same boat!  The links you posted are awesome, thank you very much for that!  It seems we are the victims of the small Canadian market.  FWIW I believe PCFin and Mint will resolve their differences eventually.  

This surely isn't the place for a PCFin/Mint conversation but I do want to add [Flinks](https://www.flinks.io/) to your list.  A Canadian version of Plaid (who I believe is the API provider to Mint) for Canadian inst's.  Their advertised free API is not free btw. :-)

Mint is fabulous for what it is, but it's not much really.

**Comment by MDrock116** [comment]
https://mintimporter.com/

**Comment by jaron-l** [comment]
I'm going to close this as it is not an issue with mintapi. As a note, you can always export to csv with mintapi and then export whatever platforms are not on mint to a common csv, combine, and then analyze the result.
