### ISSUE TITLE
transaction start date doesn't work

### ISSUE THREAD

**Issue by jeffyager** [mintapi/mintapi#174]
`mintapi --keyring --headless ********@gmail.com --extended-transactions --start-date 01/01/2019 -f output.csv`

This produces a `csv` of transactions going back as far as the account creation.

**Comment by giguerefrancoisx** [comment]
Hi Jeff, start_date requires the format '%m/%d/%y', so try '01/01/19' instead. The default behavior is to ignore formatting errors and override the start date, which is why you got the entire list of transactions instead.

**Comment by jeffyager** [comment]
Thanks for the response! Tried that with same result.  Again, not a huge deal, just wanted to report!

`mintapi --keyring --headless ********@gmail.com --extended-transactions --start-date '01/01/19' -f output.csv`

**Comment by giguerefrancoisx** [comment]
I've tried it for myself, I can't get it to work consistently either.
    data = mint.get_detailed_transactions(start_date = '01/01/19')
produces the correct output, but
    mintapi --keyring --headless ********@gmail.com --extended-transactions --start-date 01/01/19 -f output.csv
(without quotes on the date) sometimes does as you described. I've tried debugging and following the code but can't figure out why it isn't working every time.

**Comment by burkematthew** [comment]
@giguerefrancoisx @jeffyager could you try the start-date argument in the most recent version and report whether or not you're still experiencing issues?
