### ISSUE TITLE
After running, chromedriver leaves a bunch of zombies

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#190]
I'm running this as a script every hour. But chromedriver leaves behind a bunch of idle processes after every run.

Any way to get chromedriver to exit cleanly?

Thanks!

**Comment by jorythompson** [comment]
I'm having the same problem. I have a cheezy way: I look at the process list for all chrome instances and kill the ones with just a few children. It would be great if someone came up with a real solution.

**Comment by dzg** [comment]
I think I found solution...
I put a `mint.close()` at the end of my script.

**Comment by dzg** [comment]
Hmm ... not working consistently. I still have zombies. 
@mrooney any ideas?

**Comment by mrooney** [comment]
I am not familiar with this one, sorry!

**Comment by error454** [comment]
I also had this issue and in my case it looks like the problem was that my 2FA needed renewed, so my script was launching every 4 hours and just hanging waiting for the authentication code. And as a result never called mint.close() to clean up the driver.

**Comment by mrooney** [comment]
If anyone wants to try https://github.com/mrooney/mintapi/pull/220 to see if that resolves it, that'd be grand!

**Comment by jaron-l** [comment]
@dzg , there is likely an error being raised in your stdout (the console where you're running the script). Could you post it to this issue?
