### ISSUE TITLE
SQLAlchemy Classes

### ISSUE THREAD

**Issue by cornyhorse** [mintapi/mintapi#194]
I'm working on a project using this API that involves converting the JSON requests into SQLAlchemy classes.  I'm still doing some munging so right now I dump the JSON into one schema and then transform it at a later step since as far as I can tell, nobody has added anything similar to this.  

I've admittedly never contributed to something like this before but if its something you have an interest in adding, I'd be happy to see if I can get what I produce working with your codebase.  The big potential downside that I could see in my approach is that in defining a schema on the data, there might be frequent changes or many long-tail differences with the numerous financial institutions that people access Mint with.

**Comment by mrooney** [comment]
Thanks! I'm not really familiar with SQLAlchemy. What new use cases would this enable with MintAPI? It might be best as a downstream project or fork but I'm not really sure, open to your input :)

**Comment by cornyhorse** [comment]
Hey sorry, holidays so I haven't been as diligent with communication as usual! SQLAlchemy is one of the ORMs for Python.  The classes created are used to generate tables, columns, and keys; because it's ORM, its generally agnostic to the backend too. So all one has to do is point it at a database where the data is to be stored and it creates all of the tables.  From there, you can use Python to populate these tables. 

For example, right now there's some legwork to putting the data into a database:
```
accounts = mint.get_accounts(True)
for account in accounts:
    transactions = mint.get_transactions_json(id=account["id"])
    some_custom_function_to_put_transactions_in_database(transactions)
    #or use the CSV
    transactions = mint.get_transactions_csv(id=account["id"])
    transactions.to_sql(engine, transactions)
```

I elected the "some_custom_function_to_put_transactions_in_database" presently because somewhere that I can't find at the moment it mentions that JSON files are more complete or something to that effect.  

However, at the moment, I am quite reliant on PostgreSQL as a backend because it has some excellent munging features that other RDBMS don't necessarily have such as arrays, JSONB, etc.  I'd have liked to make it compatible with SQLite but it isn't quite there yet.

I tell you what, I'll try finish & clean up the repo... hopefully sometime this week... and I can share that with you.  And if there's anything you think would be useful I can try to get a PR ready for you.  I'm thinking it might make sense to add methods to the mint class for anything that has a "get_" at the moment. E.g. "get_transactions_database" so that instead of returning a JSON object and doing processing, it sends it to the database.  It definitely can be done and it definitely can be made to do SQLite which would be nice because then anyone using it wouldn't have to set up listeners or anything.  But if I made it a separate project that just uses your package upstream  I totally get it.

Failing that, I think I've documented all of the possible responses for JSON so if you'd like some additional documentation about what you can expect to get returned from these methods I can work on that too.

-Matt

**Comment by jaron-l** [comment]
Would it be easier to just use the json format from mintapi and then pandas [Dataframe::to_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html)?

I wouldn't think this something that wouldn't normally be added directly to mintapi as it seems out of scope. I'll defer to @mrooney  though as this is a grey area.

**Comment by mrooney** [comment]
Yeah, it's tough. Even documenting the JSON responses, which seems really useful on the surface, is putting stuff in docs that can change at any moment from Mint and will surely be quickly inaccurate. I could see the features you are describing being useful as a separate project that depends on mintapi, or a separate library that mintapi uses. Happy to host and support either one in this org as well.
