### ISSUE TITLE
Error: "Unable to Locate Element"

### ISSUE THREAD

**Issue by pazwicker** [mintapi/mintapi#200]
I run the `mint.get_accounts()` and `mint.get_detailed_transactions()` scrapes daily, saving results to csv. Today's attempts result in the same error for both scrapes: 

```selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="transaction"]"}```

Details:
1. mintapi v 1.41
2. Chrome driver v 79.0.3945.36
3. Selenium v 3.141.0
3. MacOS 10.15.2
4. Python 3.7.4

Thanks for developing this great tool!

**Comment by jaron-l** [comment]
Does this error continue to happen or was it only that day?

**Comment by chino** [comment]
I get random errors at times as well so I tend to just wrap it in a script that retries on failures and uses a timeout to protect against it getting stuck.

**Comment by pazwicker** [comment]
It happens periodically. I'll likely take @chino's approach for an error handler.

**Comment by mrooney** [comment]
Sounds good! Any PRs are welcome to include retry logic :)

**Comment by jaron-l** [comment]
Could one of you put the full stack trace on this issue? That will make debugging this easier for anyone that is able to pick it up.
