### ISSUE TITLE
 mint.get_invests_json() - FAIL2

### ISSUE THREAD

**Issue by j450h1** [mintapi/mintapi#219]
``` 
 # Get investments (holdings and transactions)
 mint.get_invests_json()
```
```
FAIL2
```
very strange...

**Comment by jaron-l** [comment]
What is the stack trace? And is `FAIL2` an output on your stdout? What is that coming from?

**Comment by j450h1** [comment]
Yes, FAIL2 was the output. Unfortunately, its been a while and I'm not even able to authenticate and login so can't reproduce the stack trace.
