### ISSUE TITLE
Captcha required on every login

### ISSUE THREAD

**Issue by mzakharo** [mintapi/mintapi#223]
Hello, I have had mintapi script running for a few weeks, without issues, logging in every 4 hours to pull data. but  it stopped working a few days ago. Now, every time  during the login process,  mint.com asks to solve the Google Captcha (traffic lights, etc) -> even after solving it, and logging in successfully, subsequent runs still present the Captcha.  Anyone knows a possible workaround?

**Comment by mrooney** [comment]
Thanks for the report! Did you recently update mintapi or did it stop working without any specific git pull?

**Comment by mzakharo** [comment]
Just stopped working on its own.  So I tried running the script over VPN -> and it worked, same script does not work from my home ISP.   I suspect my home IP was either manually, or automatically, blacklisted, which is interesting. Seems like me polling every 4 hours triggered some red flags.   Anyone knows what is a safe period at which to login/retrieve data from mint.com is?

**Comment by vajrang** [comment]
FWIW - this just happened to me as well.
