### ISSUE TITLE
Can't login to Mint from script anymore

### ISSUE THREAD

**Issue by gabefortinbcgs** [mintapi/mintapi#235]
Since Mint switched to having the username and passwords on separate pages mintapi can't seem to log in. Any suggestions on how I could adapt it to work? Thanks!

**Comment by mrooney** [comment]
Check out #234 and see if that doesn't address the issue! :)

**Comment by jaron-l** [comment]
Closing due to fix already being merged. Let me know if you still have issues and you can reopen the issue.
