### ISSUE TITLE
Max retries when retrieving extended transactions?

### ISSUE THREAD

**Issue by felciano** [mintapi/mintapi#236]
Hi folks --

Is anyone else having difficulty retrieving extended transactions recently? My code keeps throwing a "Max retries exceeded with url" error when trying to pull this particular data:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='mint.intuit.com', port=443): Max retries exceeded with url: /getJsonData.xevent?queryNew=&offset=24700&comparableType=8&rnd=1607362385566&accountId=0&task=transactions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2607)')))
```

This is being called from the `request_and_check` method. I've confirmed it happens with the command line client as well:

```
poetry run mintapi --keyring --mfa-method "soft-token" --mfa-token $MYTOKEN --extended-transactions $MYEMAIL
```

The issue doesn't arise with any other data request e.g. (`--accounts`, `--transactions`, `--budgets`) so I suspect it is related to the complexity or size of the extended transaction set?

Is anyone else seeing this?

**Comment by mrooney** [comment]
Could this be related to #234?

**Comment by felciano** [comment]
Maybe. I've run into that issue as well, but worked around it through repeated trial and error :-) This one, however, seems very repeatable and occurs even after a successful login with Selenium, so I suspect they are distinct.

**Comment by mrooney** [comment]
I'm going to close this out as I haven't heard of this issue recently, but please let me know if you can still reproduce it with the latest version.
