### ISSUE TITLE
No Transactions for 2021 - odate field being created with 2020

### ISSUE THREAD

**Issue by KOEPKEJR** [mintapi/mintapi#239]
My code is not seeing any transactions for 2021 when it filters on the odate field.  Investigating it appears that the following line from json_date_to_datetime is returning 2020.

`cy = datetime.isocalendar(date.today())[0]`  --> returns 2020 when 2021 is expected.

`datetime.isocalendar(date.today())` --> returns (2020, 53, 7)

Simply changing the line to `cy = date.today().year` fixed the issue for me.  Not sure what the implications are for others since there may be edge cases that I haven't considered.

It should be noted that this issue only appears during the start of the year when isocalendar goes into the 53rd week based off of some funky Thursday logic.  Once outside of this window everything will function properly.

**Comment by mrooney** [comment]
Thanks! I think date.today().year should work, do you mind sending along a PR for that?

**Comment by jaron-l** [comment]
Looks like this was already fixed as the line mentioned has been changed.
