### ISSUE TITLE
mint.get_transactions()

### ISSUE THREAD

**Issue by joelapsansky** [mintapi/mintapi#245]
Everything works for me up to this point, but when I run mint.get_transactions(), a new tab opens in the automated browser and just spins forever.

**Comment by johnjmur0** [comment]
Same thing is happening to me, just trying it for the first time.

**Comment by jaron-l** [comment]
I've been able to replicate this. It's an issue with selenium-requests not mintapi. I have a fixed version [on this branch](https://github.com/jaron-l/Selenium-Requests/tree/hotfix-handle-more-than-one). Try installing it in your environment to see if it fixes your issue. As another workaround, I've found that running headless makes it happen far less often.

**Comment by mrooney** [comment]
> I've been able to replicate this. It's an issue with selenium-requests not mintapi. I have a fixed version [on this branch](https://github.com/jaron-l/Selenium-Requests/tree/hotfix-handle-more-than-one). Try installing it in your environment to see if it fixes your issue. As another workaround, I've found that running headless makes it happen far less often.

Nice find! If you make a PR there that gets merged and released, let me know and we can update the pip version dependency on our side :)

**Comment by jaron-l** [comment]
@mrooney, selenium-requests just released a hotfix with my merge request which should fix this issue. It's version 1.3.3. It should be picked up by anyone that runs `pip install --upgrade selenium-requests`.

**Comment by mrooney** [comment]
Perfect, we've got #284 to address this and as Jaron mentioned, you can upgrade your selenium-requests manually in the meantime :)
