### ISSUE TITLE
InvalidElementStateException when logging in

### ISSUE THREAD

**Issue by henryholiday** [mintapi/mintapi#248]
Currently getting InvalidElementStateException error when trying to use the API. The script was functioning for months until last week, so this is likely due to a change on the Mint website. 

```
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/henryholiday/Documents/mint_analysis.py", line 550, in <module>
    imap_folder = 'INBOX'

  File "C:\ProgramData\Anaconda3\lib\site-packages\mintapi\api.py", line 373, in __init__
    wait_for_sync_timeout=wait_for_sync_timeout)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mintapi\api.py", line 461, in login_and_get_token
    wait_for_sync_timeout=wait_for_sync_timeout)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mintapi\api.py", line 233, in get_web_driver
    email_input.clear()

  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)

  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)

  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)

  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=88.0.4324.190)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.18363 x86_64)
```

**Comment by KOEPKEJR** [comment]
I have been getting the same error. Things seem to work 10% of the time. I would really love an option to have a screen shot taken when an error occurs with Selenium since I get different behavior when toggling headless mode. 

Recently there is another screen asking “which account” I want to use. One option is the standard Mint email address and another - I am guessing - is a TurboTax user ID I guess I made. I could see this problem affecting a smaller percentage of users.

**Comment by jasonkissinger** [comment]
I was seeing the same for last 2 days on all attempts so started investigating and got it working by hacking on the api code around mfa login.  I had been using the 1.44 pip install and just now noticed that is a 6 month old build while the src here is more up to date and handled my first hurdle (no password input).  So switched to running from src, commented out a few elements which the code expected (ie no mfa choice for me at least), and got the same "which account" screen which @KOEPKEJR saw (I also have other intuit accounts).  Hard coded it to the first account and now everything is working.

I can put my hacks out on a branch, but I'm not confident that this is the same flow for everyone.  If I get some time I'll try to make my changes less hackish.

**Comment by KOEPKEJR** [comment]
I am attempting to go down the same hacking path that @jasonkissinger mentioned.  However, when using the mintapi code I am constantly being asked to enter a 6-digit code from email.  This seems to only occur when using a Selenium-managed Chromium session.  Is anyone else being asked to enter an 2FA email code?

**Comment by pazwicker** [comment]
I followed @jasonkissinger's lead and got it working! All I did was a simple clone of this repo and moved the `api.py` file into my site packages folder, replacing the `mintapi` file that I'd installed through pip. No other actions needed on my end to get it working again. Thanks, @jasonkissinger!

**Comment by jasonkissinger** [comment]
@pazwicker, cool.  do you only have a single intuit account?  could see no changes necessary if use src build directly with single account.  the hacking i did were around mfa + multiple intuit accounts.

i also started hacking it directly in site-packages but then found what seems to be an easier/more  "proper python" way to do this is to clone the repo within my project and then `python3 -m pip install -e mintapi` to replace pip installed with my src code.  Can then mod code as you please and it'll be used directly.

**Comment by ktop77** [comment]
Mint sent out an email that i received today saying that they'll be rolling out "something big" soon, so that might throw another wrench into all this

I'm a relatively light user of this api, so not sure how the process works, but do official fixes get put in for things like this from time to time?

**Comment by pazwicker** [comment]
@jasonkissinger I do only have a single intuit account. You're right -- no src changes needed for me.

I didn't know about that "proper python" approach. Thanks for sharing!

**Comment by mrooney** [comment]
If there's any work that makes sense as a PR please do submit it and I'd be happy to review!

**Comment by KOEPKEJR** [comment]
I just want to put down some of my findings from last night incase they can help others. 

1. It seems that determining if an element is present using driver.find_element_by_id wrapped with a "try/except" no longer works well.  The majority of the elements that need to be interacted with are present (but not visible) in the DOM therefore the "try" portion always succeeds.  I ended up having to look at the element height/width to determine if it was interactable (I suspect there is a better way to do this).

2. I get different behavior when using Selenium vs. Chrome manually.  When using Selenium I am forced to use MFA with email.  There doesn't appear to be any memory of successfully authenticating the machine; each time I have to use email MFA. 

3. I get different behavior when running in headless mode. When in headed (?) mode I only have to enter the email MFA code.  When in headless I have to follow up the MFA code with my standard password.

**Comment by jasonkissinger** [comment]
i have a decent non-hack version working (with and without headless) for the no-password field on mfa and select account flows which I'm seeing for both headless and non-headless.  i'll try to get that in shape for a PR tomorrow.

also, it appears that the chrome session saving is no longer working.  i deleted the ~/.mintapi directory and it was not recreated.  possibly part of the chrome policy change on cookies they've been talking about lately.  maybe a chrome update is what caused us to all starting to see mfa prompts where we weren't before.  so i'm thinking that a good path would be to just pickle the cookies up after each session and reuse those on the next runs instead of relying on chrome session storage.  my bet is all we need it cookie to 'remember me' and stop the incessant mfa.  another benefit should work for all browsers.  i haven't looked too much into it... but may look at that later if no one beats me to it.

**Comment by brickemd** [comment]
works ok when initial login page is e-mail+password but yeah i'm struggling when first login is just e-mail. either the code is not progressing to the except of the first try/except login command (even though i'm getting element not interactable error) or something weird is happening when trying to set value of "ius-identifier".. i am very much an amateur with this stuff though so would appreciate any specific insight! thanks!

**Comment by jasonkissinger** [comment]
i've create a pull request for some changes which "works for me".  if anyone else could please take a look if it continues to work/fixes these login issues for them i'd appreciate it.

either pull my branch:  https://github.com/jasonkissinger/mintapi/tree/intuit-accounts
or apply the pr i've submitted to this project:  https://github.com/mrooney/mintapi/pull/252

i still think there is an issue with saving chrome session/cookies to "remember me" so we're not always prompted for mfa.  I'll take a look at that over next couple of days and submit something for that if I find a fix.

**Comment by jrejaud** [comment]
@jasonkissinger I pulled your branch and tried it out, it doesn't resolve the issue I've had mentioned at https://github.com/mrooney/mintapi/issues/250 thought; the email value in not inserted into the email form field on the login page, it just hangs.

Thank you for your efforts on this.

**Comment by jasonkissinger** [comment]
@jrejaud, yeah all my changes are after entering emai so wouldn't expect it to resolve hang you're seeing.   I would bet the clear() on email text field is the culprit.  I've seen selenium hang on clear on several projects.  Try commenting that out and you may get farther.

**Comment by bodhikiran** [comment]
> works ok when initial login page is e-mail+password but yeah i'm struggling when first login is just e-mail. either the code is not progressing to the except of the first try/except login command (even though i'm getting element not interactable error) or something weird is happening when trying to set value of "ius-identifier".. i am very much an amateur with this stuff though so would appreciate any specific insight! thanks!

I am facing the same issue!! Unable to get past this

**Comment by burkematthew** [comment]
Hi everyone! A fair amount of changes have occurred since the last comments. Could we get some updated status reports on if this error is still occurring? Thanks!
