### ISSUE TITLE
Please keep default functionality when adding parameters to API calls

### ISSUE THREAD

**Issue by jorythompson** [mintapi/mintapi#255]
This one only took a couple of minutes to find, but (IMHO) it should never have happened:

Referencing the Mint method:
```
    def __init__(self, email=None, password=None, mfa_method=None, mfa_token=None,
                 mfa_input_callback=None, intuit_account=None, headless=False, session_path=None,
                 imap_account=None, imap_password=None, imap_server=None,
                 imap_folder="INBOX", wait_for_sync=True, wait_for_sync_timeout=5 * 60,
                 use_chromedriver_on_path=False,
                 chromedriver_download_path=os.getcwd()):

```
For whatever reason, `use_chromedriver_on_path` was recently added to the parameter list.  I am on an ARM device (Raspberry Pi) and I have to find my own chromedriver.  Because this new variable defaulted to False, the API was over-writing my chromedriver every time it ran.

As I said, it only took a few minutes to figure out and fix my code to pass `use_chromedriver_on_path=True`, but had the developer defaulted `use_chromedriver_on_path` to False (which was the way it used to functionally work), I would never have had an issue and it would have been seamless.

Not recommending any changes to the code, just for developers to be cognizant that their changes do affect others.  Now I am wondering if there are any other changes lurking that are going to bite me later :-/

**Comment by jaron-l** [comment]
Yeah, we probably should've bumped the major version. Sorry about that. Closing as there's nothing to do here.
