### ISSUE TITLE
Possible to get accounts, budgets, and transactions simultaneously?

### ISSUE THREAD

**Issue by theurgi** [mintapi/mintapi#256]
With mintapi 1.45, Python 3.9.2, via CLI ...

```sh
mintapi --keyring --headless --accounts --budgets  --extended-transactions --start-date 04/01/21 <user@email.com>
```
... throws the following `AttributeError`:

```
File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 1469, in main
print(data.to_json(orient='records'))
AttributeError: 'dict' object has no attribute 'to_json
```

Upon investigation, it looks like the source currently doesn't logically handle getting accounts, budgets, AND transactions simultaneously—or accounts, budgets, AND any other option for that matter:

```py
if options.accounts and options.budgets:
    try:
        accounts = make_accounts_presentable(
            mint.get_accounts(get_detail=options.accounts_ext)
        )
    except Exception:
        accounts = None

    try:
        budgets = mint.get_budgets()
    except Exception:
        budgets = None

    data = {'accounts': accounts, 'budgets': budgets}
# ...
elif options.transactions:
    data = mint.get_transactions(
        include_investment=options.include_investment)

        remove_pending=options.show_pending,
            skip_duplicates=options.skip_duplicates)
# ...
```

Is this design dictated by a limitation of Mint's API?

**Comment by theurgi** [comment]
Oh right, I suppose this is because selenium or whatever would have to navigate to a different route/view to be able to scrape transaction data, therefore might as well make multiple calls externally? Is that the rational, or is there an existing way to handle this with a single call?

**Comment by burkematthew** [comment]
I have just a little more work to do on this.  Hopefully should be able to submit the PR in the next couple of days.

**Comment by burkematthew** [comment]
@theurgi I'm going to close this one as a duplicate. Please follow #344 for updates related to this request.
