### ISSUE TITLE
Password retry until lockout

### ISSUE THREAD

**Issue by DavidLangworthy** [mintapi/mintapi#263]
I have tried a number of different ways to login, but when I get to the password page some string is repeatedly entered until the too many attempts 15 minute lockout kicks in.

Any suggestions?

I'm running Python 3.8 on Windows.

**Comment by CodingPenguin** [comment]
Hey I'd like to second this, as a new MintAPI user, I've been locked out. 

Additionally, if anyone reads this, the Discord invite on the README has expired. While creating a new invite link, you can set one of the settings to "NEVER" under "Expire After".

**Comment by mrooney** [comment]
> Additionally, if anyone reads this, the Discord invite on the README has expired. While creating a new invite link, you can set one of the settings to "NEVER" under "Expire After".

Whoops, thanks, updated in the README!

**Comment by jaron-l** [comment]
@DavidLangworthy, can you give the command you are entering to cause this (python or command line)?

**Comment by DavidLangworthy** [comment]
This was from the captive browser for the amazon categorizer tool.  I attempted a repro from the mintapi command line client.  

If you're looking at this, I can try another repo this weekend.  If you'd like a particular environment let me know.  I have conda.

Thank you!

**Comment by jaron-l** [comment]
Isolating to mintapi would be helpful. Conda or cpython is fine.

On Thu, Sep 9, 2021, 9:45 AM DavidLangworthy 'notifications at github.com'
<jaron-github+reply+ADGNKUAKKOMBVJDDSCHRHMN7IX7SFEVBNHHDNFFZ24=

**Comment by DavidLangworthy** [comment]
Thanks.  Will do.
