### ISSUE TITLE
Consider using `electron` as a source for chromedriver?

### ISSUE THREAD

**Issue by cwmoriarty** [mintapi/mintapi#274]
Using mintapi on a Raspberry Pi (arch=arm64) or other ARM based SBCs isn't possible, since linux64 is x86_64/amd64

https://github.com/mrooney/mintapi/blob/91fc92eed2b3e118186a8c52aab8d4ab7e921fb8/mintapi/api.py#L183

Electron has a much greater variety of binaries, tho the mapping of Electron/Chrome version isn't super clear.
https://github.com/electron/electron/releases/tag/v14.0.0-beta.22

**Comment by jaron-l** [comment]
mintapi isn't bound to linux64. As long as you have a chrome binary, chromedriver binary, and python binary for your raspberry pi, it will work. There are already several people that have done this for the raspberry pi.

What issue are you running into exactly?

**Comment by cwmoriarty** [comment]
Oh, I can work around this just fine by hand.

It's just the 'linux64' chromedrivers available at CHROME_DRIVER_BASE_URL are x86_64/amd64 only.

**Comment by jaron-l** [comment]
I would recommend following the the instructions discussed in #282. I know it's not merged in yet but they should help.

I'm going to close this as no action is needed. Feel free to reopen if you feel otherwise.
