### ISSUE TITLE
Headless Error: Stale Element Reference

### ISSUE THREAD

**Issue by daltenbern3** [mintapi/mintapi#280]
Looks like something may have changed causing the headless call to fail. Here is the trace I am getting:

Exception: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=93.0.4577.82)
---------------------------------------------------------------------------
StaleElementReferenceException            Traceback (most recent call last)
~/PersonalFinance/code/finance.py in import_data()
     13     try:
---> 14         mint = mintapi.Mint(
     15         username,

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/mintapi/api.py in __init__(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, use_chromedriver_on_path, chromedriver_download_path)
    514         if email and password:
--> 515             self.login_and_get_token(email, password,
    516                                      mfa_method=mfa_method,

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/mintapi/api.py in login_and_get_token(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, use_chromedriver_on_path, chromedriver_download_path)
    602 
--> 603         self.driver, self.status_message = get_web_driver(
    604             email, password,

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/mintapi/api.py in get_web_driver(email, password, headless, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, session_path, imap_account, imap_password, imap_server, imap_folder, use_chromedriver_on_path, chromedriver_download_path)
    433 
--> 434     _sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, imap_account,
    435              imap_password, imap_server, imap_folder)

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/mintapi/api.py in _sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, imap_account, imap_password, imap_server, imap_folder)
    409         try:
--> 410             driver.find_element_by_id("ius-sign-in-mfa-password-collection-current-password").send_keys(password)
    411             driver.find_element_by_id("ius-sign-in-mfa-password-collection-continue-btn").submit()

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py in send_keys(self, *value)
    476 
--> 477         self._execute(Command.SEND_KEYS_TO_ELEMENT,
    478                       {'text': "".join(keys_to_typing(value)),

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py in _execute(self, command, params)
    632         params['id'] = self._id
--> 633         return self._parent.execute(command, params)
    634 

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    320         if response:
--> 321             self.error_handler.check_response(response)
    322             response['value'] = self._unwrap_value(

/products/apps/anaconda3/envs/fin_env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 

StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=93.0.4577.82)

**Comment by jaron-l** [comment]
Could you provide the basic information in our bug template?

Here's a copy of the template:

**Describe the bug**
A clear and concise description of what the bug is.

What version of MintAPI are you using?
What command[s] did you run / steps to reproduce?
Stacktrace/error received:

**What did you expect to happen?**

**What actually happened?**

**Additional context**
Add any other context about the problem here.

**Comment by daltenbern3** [comment]
Sorry I forgot to update this issue. The next day I tried again and no issue. Not sure what was the cause but can't seem to replicate anymore. Will create a new issue with more info if I see it again. Thank you!

**Comment by jaron-l** [comment]
Thanks!
