### ISSUE TITLE
Repo Management: Integrate Stale Probot Into MintApi

### ISSUE THREAD

**Issue by jaron-l** [mintapi/mintapi#285]
In the past, when trying to help people to debug their issues, I've run across the problem where users won't respond for a request for more information on their issue. I think that issues that we've responded to and asked for more information should be closed after a period of time if we receive no response.

My proposition:
Whenever a maintainer of mintapi asks for more details on a issue, he should label the issue with 'awaiting-feedback'. If the issue does not receive more comments after 60 days, then the issue is closed. We would enforce this rule with the [stale probot app](https://github.com/marketplace/stale). I would be happy to set it up if @mrooney thinks this is a good idea.

**Comment by mrooney** [comment]
That's awesome, I love that idea :) I was going through some old ones manually last night, but this will help prevent them from accumulating in the first place. Go for it!

**Comment by jaron-l** [comment]
Okay, I put in a request to have the bot installed to the mintapi organization. Let me know if that will be a problem. I'll have a pull request for the configuration setup soon.

**Comment by mrooney** [comment]
Thanks, approved!
