### ISSUE TITLE
Mintapi hangs when passed a MFA method when no MFA method is enabled in mint.com settings

### ISSUE THREAD

**Issue by revelario** [mintapi/mintapi#291]
Updated to 1.50 via pip and am able to login with `headless=False`, as long as I click on the MFA prompt manually. However, attempting to automatically login with `headless=True` hangs. Test usage below with Python 3.7.6 on Mac, Chrome Version 93.0.4577.82:

`mint = mintapi.Mint('<email>', '<password>', wait_for_sync=False, headless=True, mfa_method='sms')`

Thought it could be the same issue as/or related to #280 but I'm not getting an exception even hours after running the command. Same hanging behavior on command line with `--headless`.

**Comment by jaron-l** [comment]
Actually it sounds like #245 to me as that bug is the only one that hangs without crashing that I know of. What version of selenium-requests do you have? A recent release should have fixed it.

**Comment by revelario** [comment]
Upgraded selenium to 1.3.3 and confirmed I'm using mintapi 1.5. Restarted shell, relaunched Jupyter, but still appears to be hanging at headless login. 

![Screen Shot 2021-09-23 at 12 34 07 AM](https://user-images.githubusercontent.com/16533174/134470253-26e75f6e-7052-4bac-a2be-33dc85e614f1.jpg)
![Screen Shot 2021-09-23 at 12 34 20 AM](https://user-images.githubusercontent.com/16533174/134470269-1b1b6cd0-411f-470c-bd22-a191358dd977.jpg)

.

**Comment by revelario** [comment]
The MFA settings in Mint was a good tip. MFA was turned off in my Mint. I turned MFA "on" in Mint, and ran the same minimal example I originally posted (importing mint was the only step not shown). MFA prompt appeared, I entered the token, and was able to pull my accounts. 

Not sure why the code worked before when I never had MFA turned on in Mint, but happy that it's working again. Thank you, and let me know if you want more info.

**Comment by jaron-l** [comment]
When you were running your code and it was not working, there was no prompt for the token? I was under the impression that mint requires some sort of MFA. I'm still curious how you were experiencing that hanging.

**Comment by jaron-l** [comment]
It seems like this is a mismatch between the call arguments made to mintapi and the mint settings. It looks like if you make a cal saying there is mfa, and your mint settings don't have mfa enabled, then mintapi hangs.

**Comment by burkematthew** [comment]
So an interesting point to keep in mind here:

By default, an OTP is sent via email.  If you want, you can configure your Mint account to accept an OTP via the following:

* Text Message
* Phone Call
* Authenticator App

@jaron-l I think it's somewhat similar to what you're saying in that if the method you submit doesn't match what you have configured, you run into an issue.  As you've suggested previously, I think to resolve this we need to have a more dynamic solution to detect what type of OTP is requested and even deprecate `mfa-method`.
