### ISSUE TITLE
create issue template with common asks

### ISSUE THREAD

**Issue by mrooney** [mintapi/mintapi#295]
It looks like we can create an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) with some common things. I'm thinking something like:

* version of mintapi used?
* stacktrace/error received?
* what command did you run?
* what happened?
* what did you expect to happen?

**Comment by mrooney** [comment]
Happy to configure this but curious on your thoughts @jaron-l on anything I might be missing :)

**Comment by jaron-l** [comment]
I think this a great idea! I was going to start writing one up soon as I
find myself asking the same questions. Let's do it.

On Thu, Sep 23, 2021, 12:10 AM Michael Rooney 'notifications at github.com'
<jaron-github+reply+ADGNKUARWX2ZEDSRM4DDB4V7K7WUBEVBNHHDXZ3JUM=

**Comment by mrooney** [comment]
I didn't realize this could be done as a PR, so closing in favor of reviewing #298.
