### ISSUE TITLE
Transaction queries

### ISSUE THREAD

**Issue by chaimpeck** [mintapi/mintapi#31]
It seems like it would be really easy to add the ability to search/query the transactions. Here is a sample URL that grabs a CSV for all results that match "staples":
https://wwws.mint.com/transactionDownload.event?query=staples&queryNew=&offset=0&filterType=cash&comparableType=8

Here is a query for all transactions that were $6.90:
https://wwws.mint.com/transactionDownload.event?query=6.90&queryNew=&offset=0&filterType=cash&comparableType=8

Here are all transactions between 100 and 200 dollars:
https://wwws.mint.com/transactionDownload.event?query=100.00..200.00&queryNew=&offset=0&filterType=cash&comparableType=8

Here is a query for things matching "geico" and between 100 and 200 dollars:
https://wwws.mint.com/transactionDownload.event?query=geico%2C%20100.00..200.00&queryNew=&offset=0&filterType=cash&comparableType=8

Here are all transactions from a particular account:
https://wwws.mint.com/transactionDownload.event?accountId=6379996&query=&queryNew=&offset=0&comparableType=8

Here are all queries categorized as "student loan" and occurring between 02/01/2015 and between "02/28/2015":
https://wwws.mint.com/transactionDownload.event?startDate=02%2F01%2F2015&endDate=02%2F28%2F2015&query=category%3A%22student%20loan%22&queryNew=&offset=0&exclHidden=T&filterType=cash&comparableType=8

From the above examples, it looks like it would need to be possible to pass the parameters to get_transactions():
- query
- accountId
- startDate
- endDate

And then simply append them to the query.

```
result = self.session.get(
            'https://wwws.mint.com/transactionDownload.event',
            headers=self.headers,
            params=params
            )
```

I may end up modifying get_transactions() myself, as I would like to make a tool that can modify transactions' categories based on a query. However, if I don't get around to actually doing it, at the very least I have outlined this in a ticket so if anybody is inclined to implement this, they can.

I appreciate that this API exists and hope that I get a chance to contribute to it!

**Comment by carebdayrvis** [comment]
This is a great idea. I've modified the library myself to just query a date range of transactions.

**Comment by pca2** [comment]
Very cool. How did you discover these query string options?

**Comment by mrooney** [comment]
Good stuff! We recently released a new version that wraps get_transactions and allows obtaining CSV and JSON. If you had any interest in adding these capabilities, please do send a PR along for review and I'd be happy to incorporate it :)

**Comment by mrooney** [comment]
Closing as we do now have start and end date filtering, PRs welcome for any others!

**Comment by chaimpeck** [comment]
oh wow, heh, this was from seven years ago! I somehow missed the
comments on this. Whoops. Glad it is now implemented.
