### ISSUE TITLE
Add command-line option to control if credit accounts are excluded

### ISSUE THREAD

**Issue by burkematthew** [mintapi/mintapi#327]
If a credit report is requested, there are 3 different types of details included automatically: credit inquiries, credit accounts, and credit utilization history.  It'd be nice to have a way to isolate a certain type of that data.  To preserve existing functionality, we should add an "exclude" option for credit accounts.

**Comment by jaron-l** [comment]
> Same question, does it currently require multiple requests to get this info? I ask because if not, I'd lean towards not complicating mintapi code to do processing of data that can be easily extracted on the client side.

It does, see in [get_credit_report](https://github.com/mintapi/mintapi/blob/56c01912309dad557bd70125645ef8af994c0382/mintapi/api.py#L1151).
