### ISSUE TITLE
Mintapi fails when installing on python2.7 due to dependencies requiring python>=3.6

### ISSUE THREAD

**Issue by matt199x** [mintapi/mintapi#334]
When running "pip install mintapi" the following error occurs:

Collecting oathtool (from mintapi)
Could not find a version that satisfies the requirement oathtool (from mintapi) (from versions: )
No matching distribution found for oathtool (from mintapi)

**Comment by jaron-l** [comment]
This is likely a internet connection issue or something like that from pip
not being able to query PyPI. You'll probably be able to find the cause of
the issue from somewhere else in the error stack trace.

On Sun, Nov 7, 2021, 11:48 AM matt199x 'notifications at github.com'
<jaron-github+reply+ADGNKUFL4BVDG5R7K36JDSV7SPZH3EVBNHHD4ZIILA=

**Comment by matt199x** [comment]
I have been able to install several other items using "pip install" today. I tried on another raspberry bi and it has the same issue.

**Comment by mrooney** [comment]
Is there a full stack trace you can paste as per the bug report template?

**Comment by matt199x** [comment]
running "sudo pip3 install mintapi" instead of "pip install mintapi" fixed the issue.

**Comment by jaron-l** [comment]
I don't think this is a mintapi issue but rather something about your
python setup. I was just able to install mintapi on a raspberry pi without
sudo or any other hiccups. The full stack trace should lead you to what the
issue is.

On Sun, Nov 7, 2021, 7:03 PM matt199x 'notifications at github.com'
<jaron-github+reply+ADGNKUEX73MRKLVVPCJCFGN7SRMGLEVBNHHD4ZIILA=

**Comment by matt199x** [comment]
`pi@raspberrypi:~ $ pip install mintapi
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mintapi
  Downloading https://files.pythonhosted.org/packages/f6/94/6542c1a3d82ad599aa2bfcea4cfa10c84e99bd0ace2a830888a9993d8c84/mintapi-1.54.tar.gz
Collecting future (from mintapi)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 324kB/s 
Requirement already satisfied: mock in /usr/lib/python2.7/dist-packages (from mintapi) (2.0.0)
Collecting oathtool (from mintapi)
  Could not find a version that satisfies the requirement oathtool (from mintapi) (from versions: )
No matching distribution found for oathtool (from mintapi)
pi@raspberrypi:~ $ 
`
This was attempted on a 3b, 4 and a fresh install of Raspberry Pi OS on a 3B+. All with the same error.

**Comment by jaron-l** [comment]
Ah, that makes sense. pip is using python2.7 while when adding pip3 it is using python3. Your command switch fixes it by changing python versions, not by using sudo (which you should never do by the way. PyPI has had security vulnerabilities before and there is no need to run as sudo. If want pip to install at the user level, use the `--user` flag).

The reason your initial pip install command failed is because oathtool requires python>=3.6. We don't put a python version requirement which is why it initially worked for mintapi but failed when installing the oathtool dependency.

A fix for this would be to require python3.6. We should also remove the compatibility code.

**Comment by matt199x** [comment]
The readme should be updated to remove where it says "ensure you have python 2"
