### ISSUE TITLE
API Hangs at account selection screen

### ISSUE THREAD

**Issue by arbennet** [mintapi/mintapi#339]
I am entering my credentials directly to get going.  

<img width="307" alt="Screen Shot 2021-11-03 at 10 46 21 PM" src="https://user-images.githubusercontent.com/60998792/141374165-560a51d4-71ac-43de-a88c-1330daa507d9.png">

I can see the driver open chrome, login to my account, prompt me for an mfa token (which is sent to my email), I then enter that token in the command line, and it successfully moves to the account selection screen.  At this screen, it hangs.  It doesn't switch to the account I've selected, or click continue.

<img width="381" alt="Screen Shot 2021-11-11 at 4 50 03 PM" src="https://user-images.githubusercontent.com/60998792/141374195-2101978d-4035-41ea-9448-e4b6aa476828.png">

I'm using the most recent version of the api on python 3.8.2, which I've pip installed.

**Comment by mrooney** [comment]
Please try with the latest version of mintapi which was released recently with some improvements in this area. If it occurs again, please open a new issue with the bug template :) Thanks!
