### ISSUE TITLE
Log in to Mint not working

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#343]
mintapi Version: 1.54 (via `pip3`)

Initial Python call was getting stuck, so I tried running with `headless` off to see what was going on.  
After 'successful' log in, Mint shows this for an instant, then goes back to initial login page:  
 

![image](https://user-images.githubusercontent.com/466557/141520415-209018a6-f1cb-4f80-b6d6-7c5ef2d26ed7.png)

Tried with both `mfa_method='soft-token'` and `'sms'`.

Logging in manually in my regular Chrome works fine.

**Comment by dzg** [comment]
I "fixed" this by deleting my `session_path` folder, and letting it create a new one.

But this has happened a few times now ... is there a permanent solution?

If I use `soft-token`, can I just get rid of `session_path`?

**Comment by jaron-l** [comment]
Yeah, I've heard of this happening. I think it has to do with mint
detecting robot activity. You can certainly try getting rid of session_path
and see if you can login consistently. Let us know how it goes.

On Fri, Nov 12, 2021 at 1:13 PM dzg 'notifications at github.com'
<jaron-github+reply+ADGNKUGVTJYVZ6YTODW7QBF7TKO5DEVBNHHD5OJBUA=

**Comment by burkematthew** [comment]
@dzg I ran into that pretty frequently.  I've started using `--session-path=None` in each request to work around that issue.

**Comment by mrooney** [comment]
I also just released 1.57 to pypi with some login flow improvements, so it would be worth giving that and the other suggestions a try and reporting back!

**Comment by hudcap** [comment]
I'm having the same issue on 1.57

**Comment by kevko2020** [comment]
Still having this issue on 1.57 with session_path=None

**Comment by mrooney** [comment]
> Still having this issue on 1.57 with session_path=None

1.61 is the latest on pypi, so I'd recommend upgrading and try again!
