### ISSUE TITLE
Mint API Hanging at Account Selection Screen

### ISSUE THREAD

**Issue by arbennet** [mintapi/mintapi#346]
**Describe the bug**
API is hanging on account selection page.  Previously referenced in #339 

What version of MintAPI are you using? 1.57
What command[s] did you run / steps to reproduce?
<img width="307" alt="Screen Shot 2021-11-03 at 10 46 21 PM" src="https://user-images.githubusercontent.com/60998792/141840842-a46f7763-fdb3-4e65-befd-3ec506252962.png">

entered mfa from email in terminal

Stacktrace/error received: none. api gets stuck at account selection screen and will not continue to accounts page

**What did you expect to happen?**
Expected API to select account designated in code and continue to accounts page

**What actually happened?**
API got stuck at accounts selection page

**Additional context**
previously referenced this issue in #339

**Comment by jaron-l** [comment]
What are your MFA settings in mint.com? You check by going to mint.com (sign in) -> settings (on top bar) -> intuit account (side bar) -> Sign in and security -> two step verification

**Comment by arbennet** [comment]
@jaron-l two step auth is on configured to send text messages

**Comment by arbennet** [comment]
however when i use mintapi it is sending them to my email anyway

**Comment by junreddy** [comment]
When I use this it's stuck at this screen when I have email as my authentication. Is there a way on Mint to make email the default way to authentify? 
<img width="1200" alt="Screen Shot 2021-11-19 at 2 05 48 PM" src="https://user-images.githubusercontent.com/84739443/142680761-b67715c7-cf33-4d81-9f91-9cb5b20b6dd6.png">

**Comment by jaron-l** [comment]
@arbennet, since you are running this in GUI mode, what is the order of the pages that you see when logging in? Do you see any errors on the web page itself with something along the lines of, "Oops, there was an error, try again" and then it refreshes and puts you back at the account selection page?

**Comment by arbennet** [comment]
@jaron-l i see the home-page, then email entry, then password, then account selection.  After account selection an mfa email screen opens.  At this point there is a prompt in the terminal to enter the token, which i do.  It clicks into the next page where the account selection is available, but nothing occurs beyond this.

There are no errors on the page, and i don't see any errors in the dev tools.

**Comment by burkematthew** [comment]
@arbennet if you use `--session-path=None`, do you see any different behavior?

**Comment by arbennet** [comment]
@burkematthew the behavior is the same

**Comment by arbennet** [comment]
@burkematthew @jaron-l interestingly if i use the cli it works, it's only if i import it from python that it doens't work

**Comment by arbennet** [comment]
@jaron-l @burkematthew i noted that if you don't specify intuit_account it'll pick the default option, and this worked for me.  Although, if i had wanted to use the other one it appears it won't work

**Comment by burkematthew** [comment]
@arbennet I'm under the impression we still not have implemented the feature to choose an intuit account from the command line. See #314
