### ISSUE TITLE
bug: :bug: get_email_code hides exceptions when they happen

### ISSUE THREAD

**Issue by jaron-l** [mintapi/mintapi#362]
The convention used throughout the function `get_email_code` to just return an empty string if there is an error hides excpetions. I would suggest that we explicitly raise exceptions when errors happen else the sign workflow will just ignore the problem and fail later when signing in. I think that makes debugging issues harder.

_Originally posted by @jaron-l in https://github.com/mintapi/mintapi/pull/360#discussion_r763277466_

**Comment by mrooney** [comment]
Thanks for creating this to track that! :)

**Comment by burkematthew** [comment]
I'll take care of this once I fix up my changes in the open PR.
