### ISSUE TITLE
Getting 'string indices must be integers' when trying to pull last month's budgets

### ISSUE THREAD

**Issue by jcsacto** [mintapi/mintapi#365]
**Describe the bug**
I'm able to pull this month's budget with no problem but when I try and pull last month's I'm getting the error shown in title.  See code below.  

What version of MintAPI are you using? 1.5.3

What command[s] did you run / steps to reproduce?
#Create Budget History to get last month's budgets
budgets_ltm = mint.get_budgets(hist=2)
last_month_key=min(budgets_ltm.keys())
budgets_lm=budgets_ltm[last_month_key]
budget_lm_final = budgets_lm['spending']

cats = []
amts = []
spnt = []

for i in range(0, len(budget_lm_final)):
    dict = budget_lm_final[i]
    cats.append(dict['cat'])
    amts.append(dict['bgt'])
    spnt.append(dict['amt'])

df_budgets_lm = pd.DataFrame({'category':cats, 'budget':amts, 'spent':spnt})
Stacktrace/error received:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\JONCRO~1\AppData\Local\Temp/ipykernel_26448/975256106.py in <module>
      1 #Create Budget History to get last month's budgets
----> 2 budgets_ltm = mint.get_budgets(hist=2)
      3 last_month_key=min(budgets_ltm.keys())
      4 budgets_lm=budgets_ltm[last_month_key]
      5 budget_lm_final = budgets_lm['spending']

~\.conda\envs\mintEnv2\lib\site-packages\mintapi\api.py in get_budgets(self, hist)
   1024             parent = self.get_category_object_from_id(
   1025                 transaction["categoryId"], categories
-> 1026             )["parent"]
   1027             transaction["parentCategoryName"] = (
   1028                 "" if parent["name"] == "Root" else parent["name"]

TypeError: string indices must be integers

**What did you expect to happen?**
Expected to get  last month's budget into my dataframe
**What actually happened?**
Received the error shown above
**Additional context**
Apologies, but I mentioned this a few months back but haven't yet submitted bug report until now, if I'm missing something obvious in my code, please forgive any ignorance on my part.  I'm not a daily Python developer, more of a hobbyist.  Thanks!

**Comment by burkematthew** [comment]
Hi @jcsacto thanks for your report!  I have replicated this behavior and will work on a resolution today.  We'll keep you posted on the progress!

**Comment by burkematthew** [comment]
Hi @jcsacto, I see that you are on an older version of Mintapi.  Can you try updating to the latest version of Mintapi and see if your issue persists?  Thanks!

**Comment by jcsacto** [comment]
Hi @burkematthew unfortunately after upgrading (apologies, thought I did that with the pip upgrade method but just uninstalled and reinstalled this time) can now not even login at this point.  Receiving the error below and below that is my login script, thanks in advance for any help. 

'token'
Traceback (most recent call last):
  File "C:\Users\Jon Crosby\.conda\envs\mintEnv2\lib\site-packages\mintapi\api.py", line 791, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "C:\Users\Jon Crosby\.conda\envs\mintEnv2\lib\site-packages\mintapi\api.py", line 544, in sign_in
    return status_message, get_token(driver)
  File "C:\Users\Jon Crosby\.conda\envs\mintEnv2\lib\site-packages\mintapi\api.py", line 1424, in get_token
    return json.loads(value_json)["token"]
KeyError: 'token'

#--Login Script--
import mintapi
import pandas as pd
import gspread
import time 
from df2gspread import df2gspread as d2g 
from oauth2client.service_account import ServiceAccountCredentials
from config import username, password

mint = mintapi.Mint(
    username,  # Email used to log in to Mint
    password,  # Your password used to log in to mint
 
    # Optional parameters
    mfa_method='email',  # Can be 'sms' (default), 'email', or 'soft-token'.
                       # if mintapi detects an MFA request, it will trigger the requested method
                       # and prompt on the command line.
    headless=False,  # Whether the chromedriver should work without opening a
                     # visible window (useful for server-side deployments)
    mfa_input_callback=None,  # A callback accepting a single argument (the prompt)
                              # which returns the user-inputted 2FA code. By default
                              # the default Python `input` function is used.
    session_path=None, # Directory that the Chrome persistent session will be written/read from.
                       # To avoid the 2FA code being asked for multiple times, you can either set
                       # this parameter or log in by hand in Chrome under the same user this runs
                       # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
)

**Comment by burkematthew** [comment]
Hi @jcsacto thanks for the updated information. I'll review this and get back with you on my findings. I appreciate your patience!

**Comment by burkematthew** [comment]
@jcsacto we just released some modifications surrounding category handling. Can you test out on 1.60 and see if you still experience this issue?

**Comment by jcsacto** [comment]
@burkematthew  Everything is looking good again!  Awesome job and thanks so much for keeping me in the loop, at the moment I appear to be 'back in business'.  Happy holidays!
