### ISSUE TITLE
ci: python 3.10 builds take ~10 minutes

### ISSUE THREAD

**Issue by mrooney** [mintapi/mintapi#373]
Just opening this to track that python 3.10 builds take ~10 minutes, perhaps caused by building pandas? The other version take ~30 seconds, so this really slows down our cycle/feedback times. Curious if anyone has any ideas!

**Comment by jaron-l** [comment]
It's because the pandas version we have pinned (1.1.4) does not have a wheel version for 3.10. We should simply update the requirements file to something more recent with a 3.10 wheel.

**Comment by mrooney** [comment]
> It's because the pandas version we have pinned (1.1.4) does not have a wheel version for 3.10. We should simply update the requirements file to something more recent with a 3.10 wheel.

Ah, thanks for the pointer! Created #374 to address this :)

**Comment by mrooney** [comment]
#374 merged!
