### ISSUE TITLE
Add GitHub Action to Publish to PyPi on Release

### ISSUE THREAD

**Issue by burkematthew** [mintapi/mintapi#376]
In an effort to simplify the release process, we should add some a step to our GitHub Action Workflow to auto-publish to PyPi.

See the following documentation for a reference guide on how to do so:

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

In addition, to help smooth out the release process even more, I'd recommend implementing the whole new procedures:

1. Add a `development` branch.
2. Require all Pull Requests to be against the `development` branch.
3. When a contributor creates a new release, a Pull Request is open from `development` against `main`.
4. Then, we can implement tags\releases within our main branch to also reflect the new versions.

**Comment by burkematthew** [comment]
@mrooney I'd like to get your thoughts on the above.  Since you typically handle the releases in PyPi, I thought this could make your life a little simpler.  I also think you might need to handle it since it involves adding the PyPi credentials as a secret in the repo.

**Comment by mrooney** [comment]
Thanks for the issue and thoughts, greatly appreciated! I would say in general that managing an additional branch and potential cherry picks / merges between them, seems like more work than the process now to release from `main` as desired. I also like the idea that the goal is for `main` to always be releasable; the work is only the decision of when.

Though, if there's some way to leverage GH actions automation for this where I can click a button, that's neat too, though it is currently scripted so it's pretty simple on my end.

**Comment by burkematthew** [comment]
@mrooney just figured I'd ask on the `development` to `main` idea.  Either way is fine with me.

Do you want to pursue the use of GH Actions for releasing to PyPi?  If so, if you go through the steps to add the secrets to the repo, I can work on the Action itself to get it hooked up.  Let me know your thoughts.

**Comment by mrooney** [comment]
Sure, that sounds neat! Is my understanding correct that this would be a manual workflow, so that we could still have PRs to update the changelog/version as appropriate, but then we could navigate to the Actions tab of the repo and kick off the release via GH? If so, that sounds great! Just let me know what secrets to add :)

**Comment by burkematthew** [comment]
@mrooney the idea is that the PR for changelog and version update would trigger a GH Action that would release to PyPi.

**Comment by mrooney** [comment]
> @mrooney the idea is that the PR for changelog and version update would trigger a GH Action that would release to PyPi.

Awesome! Just to clarify, is it the creation of the PR, or the merging of the PR to main? I'd think we'd only want the latter. If so, I wonder if it could also handle tagging a release 🤔

**Comment by burkematthew** [comment]
@mrooney it'd be the merging of the PR to main. And yes I know we could do that as I've seen that done before.

**Comment by burkematthew** [comment]
@mrooney thinking about this a little more, I think the biggest trick will be to know which merge to main is supposed to trigger the action.  In most implementations I've worked with, we have the `main` and `development` branching pattern, which makes it simple that any merge to `main` triggers the flow.  I get that your point about any history on `main` is considered releaseable.  However, I think that can apply towards the `development` branch and redirect our users to work off of that branch if working from the repo.  I also think it's much more standard practice to have the `development` branch serve as the middleman between feature branches and `main`.

**Comment by burkematthew** [comment]
Also, I came across this GH Action that could be a nice addition to automating the CD of this repo: https://github.com/ardalanamini/auto-changelog

I know it doesn't take long for you to do these pieces, but it'd be nice to eliminate the need for manual intervention and simply let you focus on the more important aspects of maintaining the repo.

**Comment by burkematthew** [comment]
Bumping this so it's not stale.

**Comment by mrooney** [comment]
The auto-changelog could be neat, I'd be happy to try that! The other ideas for auto-release seem neat, but add some complication/ambiguity around when to release, and I think it is already very easy for me to run the deploy.sh script in the repo :) I'll close this one but if I've misremembered and there's some way to get just a manual button that certain folks can press, that works for me.

**Comment by burkematthew** [comment]
No problem!
