### ISSUE TITLE
Requesting CSV file for investments per cobolisalive

### ISSUE THREAD

**Issue by shumm92** [mintapi/mintapi#378]
Only JSON is available currently.

**Comment by shumm92** [comment]
Matthew thank you. I think many users would also appreciate formatting the data set using pandas.

**Comment by burkematthew** [comment]
@shumm92 FYI, you can track progress in #382 .

**Comment by burkematthew** [comment]
@shumm92 this was just merged. If you are running off of main, it's available. Otherwise, it'll be in the next release.

**Comment by shumm92** [comment]
Wow that was fast! Thank you
