### ISSUE TITLE
UnboundLocalError: local variable 'attention_msg' referenced before assignment

### ISSUE THREAD

**Issue by burkematthew** [mintapi/mintapi#379]
**Describe the bug**
When running any command-line option without specifying `attention`, an error is received.

What version of MintAPI are you using?: `1.60`
What command[s] did you run / steps to reproduce?

keyring
investments
mfa-method=email
imap-server=imap.gmail.com
imap-account=<email>
filename=investments.json

Stacktrace/error received:

UnboundLocalError: local variable 'attention_msg' referenced before assignment

**What did you expect to happen?**

Investment data is returned

**What actually happened?**

No investment data was output and an exception was raised.

**Additional context**
This was caused by #371

**Comment by mrooney** [comment]
Thanks, fixed and I'll release that as 1.61!
