### ISSUE TITLE
Uncaught Selenium Exception: StaleElementReferenceException

### ISSUE THREAD

**Issue by jeremyehack** [mintapi/mintapi#388]
**Describe the bug**
I'm running mintapi in a container headless on AWS and it has been working fine for months even through occasional Chrome and package version updates. It runs through the login flow fine, but then after it enters MFA it is erroring on a StaleElementReferenceException. I ran same script without headless mode on my Mac and was able to confirm that it is happening right after the MFA soft-token flow completes. 

What version of MintAPI are you using?
  * mintapi==1.60

What command[s] did you run / steps to reproduce?
Tried a couple ways:
  * Building driver through Chrome Opts:
    ```
        mint = mintapi.Mint()
        mint.driver = Chrome(executable_path=f'/opt/chromedriver', chrome_options=chrome_opts())
        mint.status_message, mint.token = mintapi.sign_in(email, password, driver=mint.driver, mfa_method="soft-token", mfa_token=token)
    ```
  * Using driver on path:
    `mint = mintapi.Mint(email=email, password=password, use_chromedriver_on_path=True, headless=True, mfa_method="soft-token", mfa_token=token)` 

Stacktrace/error received:
```
  (Session info: headless chrome=96.0.4664.110)

Traceback (most recent call last):
  File "/var/task/mintapi/api.py", line 235, in login_and_get_token
    self.status_message, self.token = sign_in(
  File "/var/task/mintapi/signIn.py", line 482, in sign_in
    driver.find_element_by_id(
  File "/var/task/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/var/task/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/var/task/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/var/task/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
```

**What did you expect to happen?**
Successfully login and the Mint object gets data that it is looking for

**What actually happened?**
Getting above error when using the mfa soft-token flow. 

**Additional context**
I was able to get this to run fine by installing mintapi from a local project where I added the above exception to be [caught here](https://github.com/mintapi/mintapi/blob/main/mintapi/signIn.py#L488). I didn't want to create a PR before opening an issue in case you want to throw a warning or something instead? Not sure if there are any genuine scenarios where you'd want to throw that exact Selenium exception to the users, or at least let them know we are suppressing it. Let me know if you want any more info.

**Comment by buzzeddesign** [comment]
Confirming the same issue, fixed by modifying that line 488 to this:

`except (NoSuchElementException, ElementNotInteractableException, StaleElementReferenceException):`

(thanks for showing me where to add this @jeremyehack !)

**Comment by buzzeddesign** [comment]
I am hacking, not sure exactly what is going on here - but adding this:

`driver.implicitly_wait(20)  # seconds`

...just above [that Try block](https://github.com/mintapi/mintapi/blob/1ea57748ff891d55ba1e7275a60d1214a67622c5/mintapi/signIn.py#L479) also seems to fix without ignoring the exception - not sure how long that wait needs to be.

**Comment by jeremyehack** [comment]
Good find, that is probably better than suppressing the exception. I don't think it even needs 20 seconds, I think 1-2 would be fine. I'll fiddle around with that and see what I get

**Comment by jaron-l** [comment]
`implicitly_wait` is probably not what you think it is. It sets the setting for the driver to wait for every DOM interaction. You are thinking of the builtin `time.sleep` or better yet an explicit wait.

Does the added exception handler in the except not sufficient to fix what you are seeing? If the element goes stale, it should catch the updated element on the next iteration of the while loop when using the except.

**Comment by hudcap** [comment]
> Confirming the same issue, fixed by modifying that line 488 to this:
> 
> `except (NoSuchElementException, ElementNotInteractableException, StaleElementReferenceException):`
> 
> (thanks for showing me where to add this @jeremyehack !)

Same problem, same solution.
Thanks!

@jeremyehack I would say to go for the PR, adding the `StaleElementReferenceException`
As @jaron-l pointed out, you're not suppressing the exception, but merely causing another go-round with the while-loop

**Comment by mrooney** [comment]
Awesome. please do submit a PR for that and I'm happy to review and merge it :)

**Comment by mrooney** [comment]
Created #391 to address this.

**Comment by mrooney** [comment]
#391 is merged, so this can be fixed by pulling the latest main :)

**Comment by jeremyehack** [comment]
@mrooney thanks for taking care of this, I was out of the country the past week and didn't have my laptop with me.
