### ISSUE TITLE
AttributeError: module 'mintapi' has no attribute 'Mint'

### ISSUE THREAD

**Issue by jayraguda** [mintapi/mintapi#393]
Trying to  instantiate the Mint class via the docs in pypi.org and I'm getting this error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mintapi' has no attribute 'Mint'`

**Comment by burkematthew** [comment]
@jayraguda can you attach either your script without credentials or a snippet so we can get a better idea where the issue may lie?

**Comment by jayraguda** [comment]
All I did was verbatim from the guide
`import mintapi
mint = mintapi.Mint(‘username’,’password’)`

…in the interpreter after having installed the package via pip3

**Comment by burkematthew** [comment]
@jayraguda are you still experiencing this issue?

**Comment by jayraguda** [comment]
Nope! I will close the issue now.
