### ISSUE TITLE
set/update property values

### ISSUE THREAD

**Issue by kaovilai** [mintapi/mintapi#400]
It would be awesome to bypass integration limitations of mint if I could using a cron job query data from another data provider (varo Bank in my case) using other methods and via the API update the value associated with those unsupported accounts.

For a start, a simple property value update seems to be sufficient. At later stage could involve submitting transactions.

**Comment by burkematthew** [comment]
@kaovilai thanks for reaching out. Am I correct that you are asking about using `mintapi` to update data within Mint?

**Comment by kaovilai** [comment]
> @kaovilai thanks for reaching out. Am I correct that you are asking about using `mintapi` to update data within Mint? 

Yes.

I figured since the project already have connection pieces it won't be so bad

**Comment by burkematthew** [comment]
@kaovilai the primary purpose of this project is to serve as a read-only interface with Mint. I'll defer on the final say to the original author @mrooney though.

**Comment by kaovilai** [comment]
- Since property type isn't connected to any account, there's no risk of conflict. It's either set to a number or it's not. Hence that's where I'd want to start with.

Later it would be cool to be able to mark bills as paid, partially paid etc which are features of mint already.

**Comment by mrooney** [comment]
Thanks for the comments! I view this project's intent as a read-only wrapper around Mint's website, but if someone came up with a clean PR in a separate API file, I'd definitely consider it!
