### ISSUE TITLE
It would be *~awesome~* to be able to update the notes and tags on a transaction

### ISSUE THREAD

**Issue by smolloy** [mintapi/mintapi#403]
I am working on a personal project to sync my Amazon purchase info into the transaction notes for each transaction in Mint that is from Amazon so I can better sort them.  I would love a way to update the notes and labels/tags on a transaction.  Right now, it's just a scraping API, but if I could do updates, THAT would be FANTASTIC :)

**Comment by mrooney** [comment]
Thanks! I certainly welcome any clean PRs to address this, but otherwise isn't in the scope/intentions of this project.
