### ISSUE TITLE
Selenium Requests Error

### ISSUE THREAD

**Issue by jcsacto** [mintapi/mintapi#408]
**Describe the bug**
My normal daily script run stopped a few days ago, I noticed that possibly chrome driver updated so when through all of that to make sure I had the right driver working (confirmed as I have another selenium chrome script that works fine in the same directory).  Mint looked like it was going to start working, selenium chrome browser popped up, went to the site and then it just crashes with the error below every time.  

What version of MintAPI are you using?
1.63
What command[s] did you run / steps to reproduce?

import mintapi
import pandas as pd
import gspread
import time 
from df2gspread import df2gspread as d2g 
from oauth2client.service_account import ServiceAccountCredentials
from config import username, password

mint = mintapi.Mint(
    username,  # Email used to log in to Mint
    password,  # Your password used to log in to mint
    # Optional parameters
    mfa_method='soft-token',  # See MFA Methods section
                       # Can be 'sms' (default), 'email', or 'soft-token'.
                       # if mintapi detects an MFA request, it will trigger the requested method
                       # and prompt on the command line.
    mfa_input_callback=None,  # see MFA Methods section
                              # can be used with any mfa_method
                              # A callback accepting a single argument (the prompt)
                              # which returns the user-inputted 2FA code. By default
                              # the default Python `input` function is used.
    mfa_token='LSOFVR[XXXXXXXXX]3SJJDXBKV',   # see MFA Methods section
                      # used with mfa_method='soft-token'
                      # the token that is used to generate the totp
    intuit_account=None, # account name when multiple accounts are registered with this email.
    headless=False,  # Whether the chromedriver should work without opening a
                     # visible window (useful for server-side deployments)
                         # None will use the default account.
    session_path=r"C:\Users\XXXXXXXX\Dropbox\Repos\python\mintPipeline\SessionPath", # Directory that the Chrome persistent session will be written/read from.
                       # To avoid the 2FA code being asked for multiple times, you can either set
                       # this parameter or log in by hand in Chrome under the same user this runs
                       # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
	use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
	                                 # is on the PATH (instead of downloading the latest version)
  )

time.sleep(5)

#Get transactions data
transactions = mint.get_transactions()

Stacktrace/error received:
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=53352): Max retries exceeded with url: /session/d7823210e0752bc09c8b9de4342476c3/window/handles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B825C6850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**What did you expect to happen?**
Expected to login and my script to run

**What actually happened?**
Debugged headless and window pops up but then quickly goes away and the error shows up after about 10 more seconds

**Additional context**

**Comment by mrooney** [comment]
Thanks! Did you by chance take a look at recently filed issues like https://github.com/mintapi/mintapi/issues/405 to see if that might the same?

**Comment by jcsacto** [comment]
@mrooney  According to the Discord channel it sounds like they might all be related to the new CSS changes, but I will not know until that part is fixed I guess since I seem to get a selenium server error.  I will update once I hear that other issue is addressed.  Thanks!
