### ISSUE TITLE
Selenium version 4

### ISSUE THREAD

**Issue by hudcap** [mintapi/mintapi#413]
https://github.com/mintapi/mintapi/blob/31a37db438358e356ff621a1485a719cb6428772/setup.py#L26

This is creating a dependency issue for me. I can solve it, but is there a reason for this constraint?
It came from https://github.com/mintapi/mintapi/pull/390, which has the following note: 
> My modification doesn't actually change what should be installed, it just helps pip see that selenium can't be over version 4 (which is the requirement of selenium_requests that pip ignores on older versions).

selenium_requests now supports selenium 4.1.0 as of this commit: https://github.com/cryzed/Selenium-Requests/commit/7f8eefcab692b8000713fa9c647e3b35b4a587ea and the [1.4.0 release](https://github.com/cryzed/Selenium-Requests/releases/tag/v1.4.0)

Happy to make the very complicated PR to remove it, or change it to `selenium<5.0.0` ;)

**Comment by mrooney** [comment]
This looks like the same as #412 ?

**Comment by hudcap** [comment]
Same solution, although that wasn't the error I was getting. I use mintapi in an environment where I use selenium for other purposes and I had the requirement set to version 4. Until now, I think it was keeping me on an older version of mintapi to satisfy that, but now I required 1.64 to get all the fixes you just pushed (THANK YOU!) and got a dependency resolver error.
