### ISSUE TITLE
initiate_account_refresh makes incorrect call to make_post_request

### ISSUE THREAD

**Issue by atkaiser** [mintapi/mintapi#424]
**Describe the bug**
```
File "/tmp/mint/update_account_balance.py", line 41, in <module>
    mint.initiate_account_refresh()
File "/usr/local/lib/python3.9/site-packages/mintapi/api.py", line 717, in initiate_account_refresh
    self.make_post_request(url="{}/refreshFILogins.xevent".format(MINT_ROOT_URL))
TypeError: make_post_request() missing 1 required positional argument: 'data'
```

What version of MintAPI are you using?
The master branch as of March 18th ( https://github.com/mintapi/mintapi/tree/f0d0f4dee959edaf3bfd60f6c18f8a8766fa4e86 )

What command[s] did you run / steps to reproduce?
```
import mintapi
mint = mintapi.Mint(...)
mint.initiate_account_refresh()
```

Stacktrace/error received:
See the bug description

**Additional context**

It looks like the merge of https://github.com/mintapi/mintapi/pull/421 updated the `initiate_account_refresh` method to not include any `data` object in the call to `make_post_request` which causes the exception because the method has it as a required argument.  Not really sure what the right way to fix this.  (Sorry if this already a known issue).

**Comment by burkematthew** [comment]
Hi @atkaiser and thanks for the report. The main branch is currently in progress as we work out resolutions to the changes necessary due to Mint's new UI. For the time being, if you still have the old Mint UI, I'd recommend just using the latest version on PyPi (1.64) until we can resolve these issues.

**Comment by burkematthew** [comment]
@atkaiser can you check out the branch linked here and see if that resolves your issue?  Thanks!

**Comment by atkaiser** [comment]
Looks good, tried to run the code snippet I put in the bug using your branch and didn't see any errors.  Checked that my accounts got refreshed and it looked like the did.  Thanks!

**Comment by mrooney** [comment]
Thanks for the confirmation!
