### ISSUE TITLE
Is there a way to better improve link between investment and account data?

### ISSUE THREAD

**Issue by josjaf** [mintapi/mintapi#435]
I'm using Mint 1.65 and I noticed that the old method for getting a list of all your investment positions is going to be deprecated, so I switched the new method from the get_invests_json method. 

I'm noticing that the dictionary keys are totally different, which is breaking all of my code, but the weirdest thing is that the account ids are now different and sometimes the same position in the same account is listed twice with different account ids.

Anyone else noticing this? I don't think I want to try and clean up data that I'm getting from an API. 

Any suggestions? This might be Mints fault, and not the python sdk package here.

**Comment by josjaf** [comment]
`len([i['accountId'] for i in mint.get_investment_data()])` shouldn't be equal to the length of the investments list

**Comment by burkematthew** [comment]
@josjaf we're really just making a call to the Investments endpoint and returning the data back to the enduser. We're not doing any sort of data manipulation. The transition to the new endpoint is part of the support for the new UI.

**Comment by josjaf** [comment]
Yeah that's fair, I figured that was case. This breaks my use of mint - there's no way for me to match a position / holding to an account. I can't figure out what positions are taxable / non taxable, etc.

**Comment by burkematthew** [comment]
@josjaf I will see what I can do and find that may help you out here. It may not be a quick turnaround as we're trying to get the new major version out. But we'll see what can be done to assist here. Thanks for the report!

**Comment by burkematthew** [comment]
Once V2 comes out, I'll have a chance to take a look at this.

**Comment by burkematthew** [comment]
@josjaf I only have one investment account in the data I have access to.  Is there anyway you can anonymize your output from the endpoint and supply that here so that I can review to get a feel of what's happening?  

Also, looking again at your supplied test against the length:

```
len([i['accountId'] for i in mint.get_investment_data()])
```

I'm pretty sure that's always going to give you the number of output records because your for loop will generate a list and then the length function will return the length of the list.  What were you trying to test\evaluate there?

Lastly, as it's been a couple months, can you confirm that you're still experiencing this issue?

**Comment by burkematthew** [comment]
@josjaf since this was for several months ago and was related to pre-v2 of MintAPI (and new version of Mint), can you update and see if you are still experiencing the same problems?

**Comment by josjaf** [comment]
I'll give it a try!

**Comment by burkematthew** [comment]
@josjaf what version are you running?

**Comment by josjaf** [comment]
2.7 of mintapi. I think the issue I have is what you describe under special considerations under the readme, I have mint and turbotax under the same email.

**Comment by josjaf** [comment]
Is there any way to separate them without creating a new mint account?

**Comment by burkematthew** [comment]
@josjaf not that I can speak to. That being said, I saw this article:

https://support.creditkarma.com/s/article/Linking-your-TurboTax-account-to-Credit-Karma

I wonder if there's a similar way to unlink them like this?

**Comment by josjaf** [comment]
I couldn't find anything to unlink them
