### ISSUE TITLE
Can't seem to get past the "sign-in without a password next time" page

### ISSUE THREAD

**Issue by sparky2708** [mintapi/mintapi#441]
**Describe the bug**
This library works great if it doesn't run into the "sign-in without a password next time" page:

![image](https://user-images.githubusercontent.com/11505646/161329067-67c219c3-5b5d-4797-b618-392000afeda9.png)

What version of MintAPI are you using? 
Name: mintapi
Version: 1.65
Summary: a screen-scraping API for Mint.com
Home-page: https://github.com/mintapi/mintapi
Author: Michael Rooney
Author-email: mrooney.mintapi@rowk.com
License: The MIT License
Location: c:\users\xxx\appdata\roaming\python\python38\site-packages
Requires: keyring, selenium, xmltodict, requests, configargparse, oathtool, selenium-requests, pandas
Required-by:

What command[s] did you run / steps to reproduce? 
was just trying to log in to my account

Stacktrace/error received:
N/A

**What did you expect to happen?**
Should click "Skip for Now"

**What actually happened?**
Got stuck on this page

**Additional context**

**Comment by sparky2708** [comment]
Running on Windows 10

**Comment by sparky2708** [comment]
Sometimes it also looks like this:

![image](https://user-images.githubusercontent.com/11505646/161330576-824be7b6-460d-4bf5-8c9e-67292d0e909b.png)

**Comment by burkematthew** [comment]
@sparky2708 this will be addressed in the next major version. If you run off of the main branch of the repo instead of off PyPi, you will have this situation handled.
