### ISSUE TITLE
Use Async/Await in all methods in Mint client

### ISSUE THREAD

**Issue by sparky2708** [mintapi/mintapi#442]
**Describe the bug**
Make all public methods async/await so they don’t block while they’re running as they take a very long time to run

**Comment by mrooney** [comment]
I would imagine the average use case wants to wait for the results, don't you think? If a user wants to keep doing other stuff, can't they wrap the call in an async manner to accomplish this use case?

**Comment by sparky2708** [comment]
I am using it with discord bot and mintapi blocks the current thread which makes discord api think the bot is dead since the bot is not acking ping requests. I am using executor to get around this but it would be nice if the methods were asynchronous so discord can do its thing. 

Also, I see that you do a lot of requests e.g. when you setup a connection and get budgets. You could execute all those requests in parallel and await the results of all of them. It should speedup the api considerably.

**Comment by burkematthew** [comment]
At the moment, we (for the most part) only support one data type at a time, though opening that up is on the roadmap and should be coming soon. I'll certainly keep this request in mind when implementing that and see what makes sense.

**Comment by sparky2708** [comment]
Thanks it would be great! I just saw about 50 POST requests happening when connecting and asking for budgets. Thought async/await and parallelism would definitely help there as they didn’t seem to require being run synchronously but all I was seeing was the DEBUG logs so could be wrong… was just an observation…

**Comment by burkematthew** [comment]
@sparky2708 well, what you are probably seeing is what is happening behind the scenes when Mint logs in and takes you to the homepage. Mintapi itself is not actually overloading with calls at all. It's really just log in and then the specific request, like for budgets. 

There is also the refresh step that occurs, so depending on if you want to wait for refresh or not, you could potentially skip that. 

The trick with all of this would be making sure that Mint is truly logged in and we have access to the API Key.
