### ISSUE TITLE
Cannot read properties of undefined (reading 'appExperience')

### ISSUE THREAD

**Issue by sparky2708** [mintapi/mintapi#444]
**Describe the bug**
 Cannot read properties of undefined (reading 'appExperience')

What version of MintAPI are you using?
straight from main

What command[s] did you run / steps to reproduce?
mintapi.Mint(...)

Stacktrace/error received:
Error: Message: javascript error: Cannot read properties of undefined (reading 'appExperience')
  (Session info: chrome=100.0.4896.60)
Stacktrace:
Backtrace:
    Ordinal0 [0x00927413+2389011]
    Ordinal0 [0x008B9F61+1941345]
    Ordinal0 [0x007AC658+837208]
    Ordinal0 [0x007AF064+847972]
    Ordinal0 [0x007AEF22+847650]
    Ordinal0 [0x007AF89A+850074]
    Ordinal0 [0x00804D49+1199433]
    Ordinal0 [0x007F414C+1130828]
    Ordinal0 [0x00804302+1196802]
    Ordinal0 [0x007F3F66+1130342]
    Ordinal0 [0x007CE546+976198]
    Ordinal0 [0x007CF456+980054]
    GetHandleVerifier [0x00AD9632+1727522]
    GetHandleVerifier [0x00B8BA4D+2457661]
    GetHandleVerifier [0x009BEB81+569713]
    GetHandleVerifier [0x009BDD76+566118]
    Ordinal0 [0x008C0B2B+1968939]
    Ordinal0 [0x008C5988+1989000]
    Ordinal0 [0x008C5A75+1989237]
    Ordinal0 [0x008CECB1+2026673]
    BaseThreadInitThunk [0x7693FA29+25]
    RtlGetAppContainerNamedObjectPath [0x76F97A7E+286]
    RtlGetAppContainerNamedObjectPath [0x76F97A4E+238]

**What did you expect to happen?**
no error

**What actually happened?**
error

**Comment by mrooney** [comment]
"straight from main" Please include the actual commit sha is using from source; this is not helpful in a bug report as soon as a new commit is made after your report.

**Comment by luigi311** [comment]
I am getting the same error when calling get_account_data()

Installed via 
pip install git+https://github.com/mintapi/mintapi.git@bc6e78c9be6aaa91266bc58d3189c46857f53af4

**Comment by mrooney** [comment]
> I am getting the same error when calling get_account_data()
> 
> Installed via pip install git+https://github.com/mintapi/mintapi.git@bc6e78c9be6aaa91266bc58d3189c46857f53af4

Can you try the latest from main?

**Comment by luigi311** [comment]
> Can you try the latest from main?

I did try the latest from main. bc6e78c9be6aaa91266bc58d3189c46857f53af4 is the latest main commit as of this comment still.

**Comment by felciano** [comment]
@mrooney FWIW I just tried installing [bc6e78c](https://github.com/mintapi/mintapi/commit/bc6e78c9be6aaa91266bc58d3189c46857f53af4) into a fresh env and am seeing the same error. 

In case it matters, my installation process was:

- download the latest repo as a `.zip` via GitHub web UI
- expanded the resulting `mintapi-main.zip` file
- run `poetry add ./mintapi-main` to install the package and dependencies
- run `poetry run mintapi --keyring <<myusername>>` to test it

**Comment by burkematthew** [comment]
@luigi311 @felciano do y'all have the old or new UI?

**Comment by sparky2708** [comment]
How do you tell if you have the old or new UI?

**Comment by burkematthew** [comment]
@sparky2708 what side is the navigation bar on the main menu?

**Comment by sparky2708** [comment]
Overview, etc. is on the top and “Accounts” is on the left

**Comment by burkematthew** [comment]
@sparky2708 yes you have the old UI, which explains the error you're receiving. Until your account migrates to the new UI, you will have to run off of PyPi or locally off of the 1.66 branch.

**Comment by luigi311** [comment]
Mine is at the top and i still receive the same error using 253a44e4b11d8b16ff45a3aa0faa4bed27032612

**Comment by burkematthew** [comment]
@luigi311 yes with the nav bar on the top, that means you're on the old UI, so I'd anticipate this issue.

**Comment by luigi311** [comment]
Gotcha i figured i was on the new one since i was getting captcha. How does the new UI look?

**Comment by mrooney** [comment]
> Gotcha i figured i was on the new one since i was getting captcha. How does the new UI look?

This is now covered in the [README](https://github.com/mintapi/mintapi#important-mintapi-20-vs-1x), if that doesn't address it let me know any language suggestions to make it clear :)

**Comment by luigi311** [comment]
Ahh i see i got confused reading the @sparky2708 response that you said was the old version. He said overview was at the top and accounts on the left. I took it to mean he had everything on the left with overview being the first button at the top left corner and the rest under that on the left side. Ok that makes more sense then.

**Comment by sparky2708** [comment]
How do I enable the new UI?

**Comment by luigi311** [comment]
You cant. Mint assigns it randomly to people to use the new UI vs the old UI

**Comment by chino** [comment]
> PyPi or locally off of the 1.66 branch.

PyPi as in the version from pip?

I just upgraded to latest pip which appears to be version 2.0 and now running into this issue (I'm on the old UI).

**Comment by mrooney** [comment]
Hi @chino ! At the time of that comment, 1.66 was the latest on pip, but now 2.0 is there. Since you have the old UI, you'll want to install 1.66 from pypi/source OR give [this PR](https://github.com/mintapi/mintapi/pull/470) a shot to force the new UI!

**Comment by burkematthew** [comment]
@chino see the previous comment on what to do to resolve this.
