### ISSUE TITLE
Multi-Data Support? Huh?

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#467]
Can someone explain [this?](https://github.com/mintapi/mintapi#multi-data-support)
How do I get "multiple types of data in one call to mintapi"?

**Comment by mrooney** [comment]
It means you can pass multiple arguments for the data you want, instead of just one, and it can write out multiple files. Perhaps we need an example call there :)

**Comment by dzg** [comment]
Yes an example would be super 
Thanks!

**Comment by mrooney** [comment]
@dzg let me know if #471 seems sufficient!
