### ISSUE TITLE
Are `extended-accounts` and `extended-transactions` still supported?

### ISSUE THREAD

**Issue by felciano** [mintapi/mintapi#475]
**Describe the bug**
When calling `mintapi` 2.1 from the command line with `--extended-accounts` as a parameter, you get this error:
```
mintapi: error: unrecognized arguments: --extended-accounts
```
Is this switch still available? The README says it is present but the inline help doesn't, so this may just be a documentation big.

**Comment by felciano** [comment]
On a related note, has the `--extended-transactions` option been removed in 2.x?

**Comment by burkematthew** [comment]
@felciano you are correct. We moved to reflect the API contract of Mint by having one transactions endpoint that mirrors Mint's endpoint and one accounts endpoint that mirrors Mint's endpoint. That being said, you're right that a clarification in the CHANGELOG would be helpful. That was missed in the midst of all the other changes. We can get that added.

**Comment by mrooney** [comment]
I think I got that covered at https://github.com/mintapi/mintapi/pull/477, let me know if you were seeing it anywhere else @felciano :)

**Comment by burkematthew** [comment]
@mrooney your PR definitely helps remove some of the confusion. That being said, it might be helpful to more prominently and explicitly mention in the CHANGELOG that we removed these two options to match the API contract of Mint.

**Comment by felciano** [comment]
Honestly I think these changes are big enough and backwards incompatible that it would be worth highlighting further in the README, as well as maybe having a separate piece of documentation that describes the changes in more detail. I'm in the midst of a pretty serious migration for my scripts, so would be happy to share my learnings (e.g. field mappings before to after, etc). Maybe a wiki page?

**Comment by mrooney** [comment]
@felciano awesome! If you want to submit anything to improve that docs that is super welcome. It is the top section of the README, which says to refer to the CHANGELOG for more info, and we tried to be very thorough on the 2.0 section. That said, certainly we welcome improvements. Closing this one for now based on #477 , but feel free to open an issue / PR for the general docs updates.
