### ISSUE TITLE
Can't sign in - The Multifactor Method sms supplied is not available

### ISSUE THREAD

**Issue by haritn** [mintapi/mintapi#478]
Getting this exception for past few days consistently while logging in. 

The Multifactor Method sms supplied is not available.
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\mintapi\signIn.py", line 572, in set_mfa_method
    mfa_result[SELECT_CSS_SELECTORS_LABEL]
  File "C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#ius-mfa-sms-otp-card-challenge"}
  (Session info: chrome=102.0.5005.63)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\mintapi\api.py", line 180, in login_and_get_token
    beta,
  File "C:\Users\user\Anaconda3\lib\site-packages\mintapi\signIn.py", line 385, in sign_in
    imap_folder,
  File "C:\Users\user\Anaconda3\lib\site-packages\mintapi\signIn.py", line 513, in mfa_page
    mfa_result = set_mfa_method(driver, mfa_method)
  File "C:\Users\user\Anaconda3\lib\site-packages\mintapi\signIn.py", line 584, in set_mfa_method
    "The Multifactor Method {} supplied is not available.".format(mfa_method)
RuntimeError: The Multifactor Method sms supplied is not available.
---------------------------------------------------------------------------
NoSuchElementException                    Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mintapi\signIn.py in set_mfa_method(driver, mfa_method)
    571         mfa_token_select = driver.find_element_by_css_selector(
--> 572             mfa_result[SELECT_CSS_SELECTORS_LABEL]
    573         )

~\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py in find_element_by_css_selector(self, css_selector)
    597         """
--> 598         return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
    599 

~\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py in find_element(self, by, value)
    977             'using': by,
--> 978             'value': value})['value']
    979 

~\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py in execute(self, driver_command, params)
    320         if response:
--> 321             self.error_handler.check_response(response)
    322             response['value'] = self._unwrap_value(

~\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py in check_response(self, response)
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#ius-mfa-sms-otp-card-challenge"}
  (Session info: chrome=102.0.5005.63)

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mintapi\api.py in login_and_get_token(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, use_chromedriver_on_path, chromedriver_download_path, driver, beta)
    179                 imap_folder,
--> 180                 beta,
    181             )

~\Anaconda3\lib\site-packages\mintapi\signIn.py in sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, imap_account, imap_password, imap_server, imap_folder, beta)
    384                 imap_server,
--> 385                 imap_folder,
    386             )

~\Anaconda3\lib\site-packages\mintapi\signIn.py in mfa_page(driver, mfa_method, mfa_token, mfa_input_callback, imap_account, imap_password, imap_server, imap_folder)
    512     else:
--> 513         mfa_result = set_mfa_method(driver, mfa_method)
    514     mfa_token_input = mfa_result[0]

~\Anaconda3\lib\site-packages\mintapi\signIn.py in set_mfa_method(driver, mfa_method)
    583         raise RuntimeError(
--> 584             "The Multifactor Method {} supplied is not available.".format(mfa_method)
    585         )

RuntimeError: The Multifactor Method sms supplied is not available.

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-9-75c34947e04b> in <module>
     35         use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
     36                                          # is on the PATH (instead of downloading the latest version)
---> 37     driver=None        # pre-configured driver. If None, Mint will initialize the WebDriver.
     38   )
     39 

~\Anaconda3\lib\site-packages\mintapi\api.py in __init__(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, use_chromedriver_on_path, chromedriver_download_path, driver, beta)
    111                 chromedriver_download_path=chromedriver_download_path,
    112                 driver=driver,
--> 113                 beta=beta,
    114             )
    115 

~\Anaconda3\lib\site-packages\mintapi\api.py in login_and_get_token(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, use_chromedriver_on_path, chromedriver_download_path, driver, beta)
    185             self.driver.quit()
    186             self.driver = None
--> 187             raise Exception(msg) from e
    188 
    189     def get_attention(self):

Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D20c017bf-c368-47a1-b279-b5f1e1440c05

**Comment by burkematthew** [comment]
@haritn are you submitting an MFA method to the Mint object? If so, please try removing that (no longer needed in V2) and see if you get different results.

**Comment by haritn** [comment]
I am not and still getting this error.  I am simply copying and pasting the code from the readme file below. Are you suggesting I turn off the mfa? 
``
import mintapi
  mint = mintapi.Mint(
    'your_email@web.com',  # Email used to log in to Mint
    'password',  # Your password used to log in to mint
    # Optional parameters
    mfa_method='sms',  # See MFA Methods section
                       # Can be 'sms' (default), 'email', or 'soft-token'.
                       # if mintapi detects an MFA request, it will trigger the requested method
                       # and prompt on the command line.
    mfa_input_callback=None,  # see MFA Methods section
                              # can be used with any mfa_method
                              # A callback accepting a single argument (the prompt)
                              # which returns the user-inputted 2FA code. By default
                              # the default Python `input` function is used.
    mfa_token=None,   # see MFA Methods section
                      # used with mfa_method='soft-token'
                      # the token that is used to generate the totp
    intuit_account=None, # account name when multiple accounts are registered with this email.
    headless=False,  # Whether the chromedriver should work without opening a
                     # visible window (useful for server-side deployments)
                         # None will use the default account.
    session_path=None, # Directory that the Chrome persistent session will be written/read from.
                       # To avoid the 2FA code being asked for multiple times, you can either set
                       # this parameter or log in by hand in Chrome under the same user this runs
                       # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
	use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
	                                 # is on the PATH (instead of downloading the latest version)
    driver=None        # pre-configured driver. If None, Mint will initialize the WebDriver.
  )

  # Get account information
  mint.get_account_data()
``

**Comment by burkematthew** [comment]
@haritn based on what you sent, it does look like you are passing an MFA method of SMS. I'd imagine that's the issue here. MintAPI detects which MFA method should be used based on what Mint presents to the user. The only time you need to pass one is if you get the screen at login asking which MFA method you want to use.
