### ISSUE TITLE
get_transaction_data() returns list instead of dataframe

### ISSUE THREAD

**Issue by Deepak-01** [mintapi/mintapi#479]
I upgraded to mintAPI version 2.0  and get_transaction_data() now returns a list instead of a dataframe. The comments suggest that that shouldn't be the case. Is there something i'm missing here that is causing this issue?

**Comment by gabefortin** [comment]
I am getting the same behaviour in version 2.1.

**Comment by burkematthew** [comment]
@Deepak-01 this is just a documentation issue. This is expected behavior in V2.

**Comment by mrooney** [comment]
I think this is mentioned in the CHANGELOG: https://github.com/mintapi/mintapi/blob/main/CHANGELOG.md. Any feedback welcome on a better place or wording for this!
