### ISSUE TITLE
Enhancement: flag or exit code if timeout

### ISSUE THREAD

**Issue by felciano** [mintapi/mintapi#483]
On occasion (see #154), `mintapi` still prints out 
```
Mint sync apparently incomplete after timeout. Data retrieved may not be current.
```
which seems related to something on the server side. Other than this message, there doesn't appear to be a way to tell whether the operation has completed successfully or not. Would it be possible to return a different exit code or provide some sort of machine-parseable result to indicate scenarios when the output data may not be correct / current?

**Comment by felciano** [comment]
I suspect a JSON error response would eventually be a good idea, but you are right that the CLI UX is non-obvious if you are requesting data in a given serialized format.

My thinking is that the non-zero exit code would be a minimum implementation, because a calling shell script could at least try some simple error handling (e.g. retry or exit), rather than proceeding as if everything is OK.

**Comment by mrooney** [comment]
As I think about it more, I'm curious if this actually warrants a non-zero exit code. It seems that mintapi was able to do its thing, it just isn't sure that all your data is current on the Mint.com side. @burkematthew any thoughts?

**Comment by burkematthew** [comment]
I think it would make sense to add an option (defaults to off for now to avoid breaking changes for users) that controls whether or not we terminate when sync fails. Is this what you are looking for in a nutshell, @felciano ?

**Comment by felciano** [comment]
Yes, provided there is also a way to determine whether the run was successful or not (e.g. exit code)

**Comment by mrooney** [comment]
That seems reasonable! We could call it `--fail-on-stale` (it rhymes!) and then exit with a unique exit code in that scenario.

**Comment by burkematthew** [comment]
Sounds good to me and easy enough.
