### ISSUE TITLE
after switching to new api, missing "note" and "labels" fields -- which are very critical for me

### ISSUE THREAD

**Issue by areagu** [mintapi/mintapi#491]
the older api used to return "note" and "labels" fields
both fields are also available in transactions.csv file that you can download from transactions tab mint.com (all the way on the bottom where pagination is)

the new api returns something called etag -- numerical value -- not sure if its related to tags (labels) and if there is another end point that will return tag names based on tag ids 

i see that others are experiencing same issue: https://www.reddit.com/r/mintuit/comments/v1bu86/filter_by_transactions_without_a_tag_or_get_back/

**Comment by CalvinChanCan** [comment]
Hi @areagu. Which method are you calling that you're not seeing the note and labels field? I've been using `get_transaction_data` which returns a json/dictionary containing `tagData` (which is the labels field) and "notes".

**Comment by areagu** [comment]
i'm calling get_transaction_data() on the new API
below is an example of a record that i'm getting back, I do get etag -- but i'm not sure how to get labels and notes from etag...

{
'type': 'CashAndCreditTransaction', 
'id': '63647170_2229459791_0', 
'accountId': '63364170_4894910', 
'accountRef': {'id': '4894910', 'name': 'Joint Checking', 'type': 'BankAccount', 'hiddenFromPlanningAndTrends': False}, 
'date': '2022-06-23', 
'description': 'SageSure Insuran VENDOR PMT', 
'category': {'id': '63647170_30', 'name': 'Income', 'categoryType': 'INCOME', 'parentId': '63647170_0', 'parentName': 'Root'}, 
'amount': 628.0, 
'status': 'POSTED', 
'matchState': 'NOT_MATCHED', 
'fiData': {'id': '17403630164', 'date': '2022-06-23', 'amount': 628.0, 'description': 'SageSure Insuran VENDOR PMT', 'inferredDescription': 'SageSure Insuran VENDOR PMT', 'inferredCategory': {'id': '63647170_30', 'name': 'Income'}}, 
'isReviewed': False, 
'etag': '1656091317000', 
'isExpense': False, 
'isPending': False, 
'discretionaryType': 'NONE', 
'isLinkedToRule': False, 
'transactionReviewState': 'UNREVIEWED', 
'lastUpdatedDate': '2022-06-24T17:21:57Z'
},

**Comment by CalvinChanCan** [comment]
That particular example you showed might not have a note and label. For example one of my transactions might look like this.
```
{
    "type": "CashAndCreditTransaction",
    "id": "12345678_2134262813_0",
    "accountId": "12345678_12345678",
    "accountRef": {
        "id": "12345678",
        "name": "Some Credit Card x1234",
        "type": "CreditAccount",
        "hiddenFromPlanningAndTrends": false
    },
    "date": "2020-12-26",
    "description": "TST* MAMALEH'S DELICATESS",
    "notes": "Lunch", <-- Note here
    "parentId": "12345678_2130124308_0",
    "category": {
        "id": "12345678_707",
        "name": "Restaurants",
        "categoryType": "EXPENSE",
        "parentId": "12345678_7",
        "parentName": "Food & Dining"
    },
    "tagData": { <-- Label is here
        "tags": [{
                "id": "12345678_2558202",
                "name": "Calvin",
                "hiddenFromPlanningAndTrends": false
            }
        ]
    },
    "amount": -9.95,
    "status": "POSTED",
    "matchState": "NOT_MATCHED",
    "fiData": {
        "date": "2020-12-26",
        "amount": -29.84,
        "description": "TST* MAMALEH'S DELICATESS",
        "inferredDescription": "TST* MAMALEH'S DELICATESS",
        "inferredCategory": {
            "id": "12345678_707",
            "name": "Restaurants"
        }
    },
    "isReviewed": false,
    "etag": "1234567891234",
    "isExpense": true,
    "isPending": false,
    "discretionaryType": "DISCRETIONARY",
    "isLinkedToRule": false,
    "transactionReviewState": "UNREVIEWED",
    "lastUpdatedDate": "2021-01-09T17:20:50Z"
}
```

**Comment by areagu** [comment]
omg you're totally right -- thank you so much !

**Comment by burkematthew** [comment]
Nice catch @CalvinChanCan and @areagu I'm glad that your issue is not really an issue!
