### ISSUE TITLE
Could not sign in to Mint. Current page: https://mint.intuit.com/overview?utm_medium=direct&cta=nav_login_dropdown&ivid=6276225c-b1e6-403b-b256-1f73381426ee

### ISSUE THREAD

**Issue by YusufBritton1990** [mintapi/mintapi#508]
**Describe the bug**
After the mint API signs in with my email and password, I input the MFA sms prompt in my gitbash. after I input this in, I get this error below:
Could not sign in to Mint. Current page: https://mint.intuit.com/overview?utm_medium=direct&cta=nav_login_dropdown&ivid=6276225c-b1e6-403b-b256-1f73381426ee

Since the MFA is the only MFA option in my mint account, I have mfa_method commented out.

What version of MintAPI are you using? 2.4

What command[s] did you run / steps to reproduce?
def ingest_transactions(request):
    # TODO: See why ingestion isn't working passed 3-4

    context = {}

    # Connect to DB model
    trans_qs = Transactions.objects.all()

    # Delete a month worth of data to reduce duplicates
    last_updated = trans_qs.latest('trans_date').trans_date

    days = datetime.timedelta(30)
    last_updated = last_updated - days
    trans_qs.filter(trans_date__gte=last_updated).delete()

    # Retrieve data from mint (you can put your values in)
    MINT_EMAIL = MINT_EMAIL 
    MINT_USER = MINT_USER 
    MINT_PASS = MINT_PASS 

    mint = mintapi.Mint(
    MINT_EMAIL,  # Email used to log in to Mint
    MINT_PASS,  # Your password used to log in to mint
    # Optional parameters
    # mfa_method='sms',  # See MFA Methods section
                   # Can be 'sms' (default), 'email', or 'soft-token'.
                   # if mintapi detects an MFA request, it will trigger the requested method
                   # and prompt on the command line.
    mfa_input_callback=None,  # see MFA Methods section
                          # can be used with any mfa_method
                          # A callback accepting a single argument (the prompt)
                          # which returns the user-inputted 2FA code. By default
                          # the default Python `input` function is used.
    mfa_token=None,   # see MFA Methods section
                  # used with mfa_method='soft-token'
                  # the token that is used to generate the totp
    intuit_account=None, # account name when multiple accounts are registered with this email.
    headless=False,  # Whether the chromedriver should work without opening a
                 # visible window (useful for server-side deployments)
                     # None will use the default account.
    session_path=None, # Directory that the Chrome persistent session will be written/read from.
                   # To avoid the 2FA code being asked for multiple times, you can either set
                   # this parameter or log in by hand in Chrome under the same user this runs
                   # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
    fail_if_stale=True, # True will raise an exception if Mint is unable to refresh your data.
    use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
                                 # is on the PATH (instead of downloading the latest version)
    driver=None        # pre-configured driver. If None, Mint will initialize the WebDriver.
    )

    """Accounts"""
    # Step 1: Loop through accounts

    accounts = mint.get_account_data()
    for mint_acct in accounts:
        mint_acct_name = mint_acct['accountName']

        print(f'checking for account: {mint_acct_name}')

        # Step 2: Check if account if closed
        if mint_acct['isClosed']:
            #In Prod, will continue the loop
            print(f'{mint_acct_name} is closed')

            if Accounts.objects.filter(acct_name=mint_acct_name).exists():
                Accounts.objects.filter(acct_name=mint_acct_name).delete()
                print(f'{mint_acct_name} is a old account. Deleting')

            print('\n')
            continue
        else:
            #In Prod, will continue with validating account
            print(f'{mint_acct_name} is open')

        # Step 3: Confirm if account exist, if not, create the account in DB
        if Accounts.objects.filter(acct_name=mint_acct_name).exists():
            print(f'Updating {mint_acct_name} balance')
            acct = Accounts.objects.filter(acct_name=mint_acct_name)

            acct.update(
            balance=mint_acct['currentBalance'],
            update_date=mint_acct['fiLastUpdatedInDate']
            )

        else:
            auto_id = Accounts.objects.all().values_list(
                'acct_id', flat=True).order_by('-acct_id').first()

            auto_id = auto_id + 1

            print(f'Creating new account: {mint_acct_name}')
            acct = Accounts.objects.create(
                acct_id=auto_id,
                acct_name=mint_acct_name,
                acct_trans_type="credit",
                balance=mint_acct['currentBalance'],
                update_date=mint_acct['fiLastUpdatedInDate']
            )

        print('\n')

    """Transactions"""

    # retri transactions from a certain date
    # start_dte = trans_qs.values_list('trans_date', flat=True).order_by('-trans_date').first()
    # days = datetime.timedelta(60)
    # start_dte = start_dte - days
    # start_dte = start_dte.strftime("%#m/%d/%y")

    # trans_new_df =  mint.get_transaction_data(start_date=start_dte) # as pandas dataframe

    trans_new_df =  mint.get_transaction_data() # as pandas dataframe

    debit_df = trans_new_df[trans_new_df.transaction_type == 'debit']
    credit_df  = trans_new_df[trans_new_df.transaction_type == 'credit']

    debit_df['amount'] *=  -1.0

    trans_new_df = pd.concat([debit_df, credit_df], ignore_index=True)

    # Retrieve data from mint (using test file)
    BASE_PATH = Path(os.getcwd()).parents[0]
    file_path = os.path.join(BASE_PATH,'data', 'transactions.csv')
    #
    # trans_df = pd.read_csv(file_path)
    #
    # trans_new_df = trans_df[0:5]
    # trans_new_df = trans_df

    # subset new transactions
    # https://stackoverflow.com/questions/11697887/converting-django-queryset-to-pandas-dataframe
    trans_db_df = pd.DataFrame(list(trans_qs.values()))
    trans_db_df['trans_date'] = pd.to_datetime(trans_db_df["trans_date"])
    # trans_db_df['trans_date'] = trans_db_df["trans_date"].dt.strftime("%#m/%d/%Y")

    trans_insert = trans_db_df.merge(trans_new_df, how = 'right',
    left_on = ['description', 'amount','trans_type', 'trans_date','category'],
    right_on=['description', 'amount', 'transaction_type', 'date', 'category'],
        indicator=True)

    trans_insert = trans_insert[trans_insert['_merge'] == 'right_only'] #new transactions
    trans_insert = trans_insert.sort_values(by=['date'])

    # # Insert new transactions
    model_instances = []

    auto_id = trans_qs.values_list('trans_id', flat=True).order_by('-trans_id').first()
    auto_id = auto_id + 1 #new ID to generate for bulk

    trans_insert['date'] = pd.to_datetime(trans_insert['date']) #date format
    trans_insert['category'] = trans_insert['category'].str.title()

    # df_records = trans_insert.to_dict('records')
    df_records = trans_insert.to_dict('records')
    for record in df_records:
        model_instances.append(
            Transactions(
                trans_id=auto_id,
                description=record['description'],
                orig_description=record['original_description'],
                amount=record['amount'],
                trans_type=record['transaction_type'],
                category=record['category'],
                acct_id=Accounts.objects.get(acct_name=record['account_name']),
                labels=record['labels_y'],
                notes=record['notes_y'],
                trans_date=record['date'],)
        )

        auto_id += 1

    Transactions.objects.bulk_create(model_instances)

    # Remove duplicates
    unique_fields = ['description', 'amount', 'trans_type', 'category', 'acct_id', 'trans_date']

    print(f'Removing any duplicate tranactions')

    duplicates = (
    trans_qs.values(*unique_fields)
    .order_by()
    .annotate(min_id=Min('trans_id'), count_id=Count('trans_id'))
    .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            trans_qs.filter(**{x: duplicate[x] for x in unique_fields})
            .exclude(trans_id=duplicate['min_id'])
            .delete()
        )

    context['cwd'] = file_path
    context['data'] = trans_new_df[-20:].to_html()
    context['data_db'] = trans_db_df[-20:].to_html()
    context['data_insert'] = trans_insert[-20:].to_html()
    context['dtypes'] = trans_new_df.dtypes
    context['dbdtypes'] = trans_db_df.dtypes
    # context['start_dte'] = start_dte

    return render(request, 'budget/ingestion.html', context)

Stacktrace/error received:
Environment:

Request Method: GET
Request URL: http://localhost:8000/ingest_transactions

Django Version: 3.2.13
Python Version: 3.7.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'budget.apps.BudgetConfig',
 'django_extensions',
 'django_tables2',
 'django.contrib.humanize',
 'bootstrap_datepicker_plus']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\mintapi\api.py", line 184, in login_and_get_token
    beta,
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\mintapi\signIn.py", line 394, in sign_in
    account_selection_page(driver, intuit_account)
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\mintapi\signIn.py", line 674, in account_selection_page
    "[data-testid='SelectAccountContinueButton']",
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)

The above exception (Message: 
) was the direct cause of the following exception:
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Youth\Desktop\budget\budgetsite\budget\views.py", line 241, in ingest_transactions
    driver=None        # pre-configured driver. If None, Mint will initialize the WebDriver.
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\mintapi\api.py", line 115, in __init__
    beta=beta,
  File "C:\Users\Youth\Desktop\budget\budgetsite\env\lib\site-packages\mintapi\api.py", line 191, in login_and_get_token
    raise Exception(msg) from e

Exception Type: Exception at /ingest_transactions
Exception Value: Could not sign in to Mint. Current page: https://mint.intuit.com/overview?utm_medium=direct&cta=nav_login_dropdown&ivid=6276225c-b1e6-403b-b256-1f73381426ee

**What did you expect to happen?**
As in version 1, log in and get accoutn and transaction data.

**What actually happened?**
connection broke after inputting MFA

**Additional context**

Here is my mint instance for reference. My nav bar is to the left
mint = mintapi.Mint(
    MINT_EMAIL,  # Email used to log in to Mint
    MINT_PASS,  # Your password used to log in to mint
    # Optional parameters
    # mfa_method='sms',  # See MFA Methods section
                   # Can be 'sms' (default), 'email', or 'soft-token'.
                   # if mintapi detects an MFA request, it will trigger the requested method
                   # and prompt on the command line.
    mfa_input_callback=None,  # see MFA Methods section
                          # can be used with any mfa_method
                          # A callback accepting a single argument (the prompt)
                          # which returns the user-inputted 2FA code. By default
                          # the default Python `input` function is used.
    mfa_token=None,   # see MFA Methods section
                  # used with mfa_method='soft-token'
                  # the token that is used to generate the totp
    intuit_account=None, # account name when multiple accounts are registered with this email.
    headless=False,  # Whether the chromedriver should work without opening a
                 # visible window (useful for server-side deployments)
                     # None will use the default account.
    session_path=None, # Directory that the Chrome persistent session will be written/read from.
                   # To avoid the 2FA code being asked for multiple times, you can either set
                   # this parameter or log in by hand in Chrome under the same user this runs
                   # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
    fail_if_stale=True, # True will raise an exception if Mint is unable to refresh your data.
    use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
                                 # is on the PATH (instead of downloading the latest version)
    driver=None        # pre-configured driver. If None, Mint will initialize the WebDriver.
    )

**Comment by createav** [comment]
I am getting the same error here. 4.2.

In non-headless mode and I am getting through login then receiving recaptcha screen with the "make sure your not a robot" screen. It's the only consistent part about getting this error.

**Comment by burkematthew** [comment]
This is a known issue. The wait on the Account Selection Page isn't long enough, resulting in the Timeout Error. We need to increase the value.

**Comment by matt199x** [comment]
I have the same issue. My temporary fix is to uncomment "mfa_method='sms'" put the mfa code in then comment out the line again. It will work for a week or two in my case.

**Comment by burkematthew** [comment]
@matt199x with v2, you shouldn't need to send `mfa_method='sms'` in the first place.  That being said, the attached PR should ideally take care of this issue.

**Comment by YusufBritton1990** [comment]
I have the mfa_method='sms' commented, but I am still getting the same error.
