### ISSUE TITLE
[Enhancement Request] Allow search criteria for transactions

### ISSUE THREAD

**Issue by RyanKohn** [mintapi/mintapi#509]
Doing a POST to /transactions/search allows you to provide criteria for your search via various parameters.

The general body of the request looks something like this:
```
{
   "limit":100,
   "offset":0,
   "searchFilters":[
      {
         "matchAll":true,
         "filters":[
            {
               "type":"CategoryIdFilter",
               "categoryId":"123456000_12034",
               "includeChildCategories":true
            },
            {
               "type":"TagNameFilter",
               "tagName":"Reviewed Transactions"
            }
         ]
      }
   ],
   "dateFilter":{
      "type":"CUSTOM",
      "endDate":"2023-07-04",
      "startDate":"2007-01-01"
   },
   "sort":"DATE_DESCENDING"
}
```

Note that it is possible to combine multiple filters in a single request. The `matchAll` parameter determines whether the combination is treated as an All (`matchAll=true`) or an Any (`matchAll=false`).

Using Fiddler, I inspected a number of different filter requests submitted through the UI, and was able to discover several variations on the allowed filters. I don't know if the below is an exhaustive list, but including the examples that I found:

**General search text (similar to just typing text into the search box in the UI):**
```
{
   "type":"TransactionLiteralFilter", //required field
   "searchFilter":"<search text>" //required field
}
```

**Search by Category Id (you would need to inspect elements to know your personal category IDs):**
```
{
   "type":"CategoryIdFilter", //required field
   "categoryId":"#####_####", //required field
   "includeChildCategories":true, //required field
   "exclude":true //optional field
}
```

**Search by Category Name:**
```
{
   "type":"CategoryNameFilter", //required field
   "categoryName":"<category name>", //required field
   "includeChildCategories":true, //required field
   "exclude":true //optional field
}
```

**Search by Tag Id (you would need to inspect elements to know your personal tag IDs):**
```
{
   "type":"TagIdFilter", //required field
   "tagId":"#####_#####", //required field
   "exclude":true //optional field
}
```

**Search by Tag Name:**
```
{
   "type":"TagNameFilter", //required field
   "tagName":"<tag name>", //required field
   "exclude":true //optional field
}
```

**Search by transaction description:**
```
{
   "type":"DescriptionNameFilter", //required field
   "description":"<description text>", //required field
   "exclude":false //optional field
}
```

**Filter by Account Type:**
```
{
   "type":"AccountTypeFilter", //required field
   "accountType":"BankAccount", //required field (BankAccount, CreditAccount, LoanAccount, InvestmentAccount, CashAccount)
}
```

**Filter by Account Id (you would need to inspect in order to get your specific account IDs):**
```
{
   "type":"AccountIdFilter", //required field
   "accountId":"#####_#####", //required field
}
```

**Comment by burkematthew** [comment]
This is my next-up project.
