### ISSUE TITLE
Not working – not filling in password

### ISSUE THREAD

**Issue by dzg** [mintapi/mintapi#519]
**Describe the bug**
```
mint = mintapi.Mint(email, password,
   mfa_method='soft-token', mfa_token=token 
)
```
gets as far as "enter password" then does not fill in password. Was working a couple of weeks ago.

```
pip list | grep mintapi
mintapi                  2.5
```

**Comment by burkematthew** [comment]
@dzg please see @hudcap 's comment and verify if main fixes your issue.

**Comment by zosky** [comment]
wifeee mentioned our webUI is blank. downgraded chrome+driver to 102 (as mentioned on another thread) which made it stop crashing, but stuck at pw. confirming main is now able to enter the pw again

this whole flow was stable for years. for your sanity, i really hope they stabilize their new UI soon. 

**thanks for making this easy _-ish_ !!**

**Comment by bcn76** [comment]
> @dzg please see @hudcap 's comment and verify if main fixes your issue.

I was having the same error and same location mintapi was stalling, I switched from the default pip install to
pip install https://github.com/mintapi/mintapi/archive/main.zip
and the problem has resolved, thanks!
