### ISSUE TITLE
Descrepency between what is reported by the json net_worth output and what is shown on the web page

### ISSUE THREAD

**Issue by mdupuy** [mintapi/mintapi#527]
net_worth reports a value that is $130k higher than what is reported by the actual web page
Any idea why that might be?

**Comment by mrooney** [comment]
Can you please use the bug template to include your version of mintapi, the call you are using, and any screenshots to demo this? We don't have any information needed to debug this.

**Comment by mdupuy** [comment]
Sorry, version of mintapi is current (2.6)
Running on Chrome Version 103.0.5060.114 (Official Build) (arm64)
ChromeDriver 103.0.5060.53
Python 3.9.13
MacOS 12.4 (21F79)

json from mintapi:
{
  "net_worth": 1707764.8900000001
}

Screen Grab:
![browser screen grab](https://user-images.githubusercontent.com/1259611/180111795-e6825957-b906-4fc5-b43e-37e31202cb76.jpg)

A difference of 127,570.63
Nothing in my accounts seems to add up to that amount.

**Comment by mrooney** [comment]
Sorry if this is a really dumb question, but you are definitely using the same account for the web vs mintapi, right? :D

**Comment by burkematthew** [comment]
@mdupuy my best advice for you is to export your account data and then perform a manual calculation similar to our handling: taking active accounts, you subtract the current balance of Loan and Credit Accounts from the current balance of all other accounts.  This is what your true Mint "Net Worth" would be.  You also may check the Trend of your Net Worth (which you can pull using MintAPI now) and see if you notice where any sort of "deviation" might come into play.
