### ISSUE TITLE
Some mint accounts have multiple accounts, stuck in selection screen loop

### ISSUE THREAD

**Issue by karunkrishna** [mintapi/mintapi#529]
When a mint account has multiple selections, the mintapi get stuck on the printscreen below. 
Is it possible to select the latest date or ratio button automatically to continue. 

I need to run in headless=False mode, manually select to continue, before the rest of my script can run. So I can't migrate this code to AWS lambda or run from docker. Has anyone experienced this. I am willing to delete the old account if it does not accidently delete any data for the new account

![image](https://user-images.githubusercontent.com/2157606/180102663-519888a2-9cdd-458a-98ae-8d8ee363b3e0.png)

**Comment by burkematthew** [comment]
@karunkrishna what version are you running?

**Comment by karunkrishna** [comment]
mintapi==2.6

**Comment by burkematthew** [comment]
Thanks @karunkrishna , it appears I'm experiencing the same issue.  I'll take a look at it!
