### ISSUE TITLE
CSV field order

### ISSUE THREAD

**Issue by rchadgray** [mintapi/mintapi#534]
Every time i create a CSV file the data is organized differently.  Transactions is where i have noticed it.

This makes it difficult to use bulk insert of data into databases if the fields are not in the same order each time.

Export1 example:
type,id,accountId,date,description,amount,status,matchState,etag,isExpense,isPending,discretionaryType,isLinkedToRule

Export2 example:
type,id,accountId,date,description,amount,status,matchState,merchantId,etag,isExpense,isPending,discretionaryType,isLinkedToRule

**Comment by burkematthew** [comment]
@rchadgray this order is defined by Mint.  The only option we'd have is to alphabetize the columns, but that would more than likely negatively affect more users than help as it would change the contextual order of the columns.
