### ISSUE TITLE
get_transaction_data not downloading all transactions.

### ISSUE THREAD

**Issue by noblevirk** [mintapi/mintapi#537]
**Describe the bug**
Not sure if this is a bug or not, but it seems like that my connection to mint is getting closed prematurely. I set the
`wait_for_sync_timeout=10*60` and I'm sure the connection is interrupted way before this timer is done. I think as a result, I'm only receiving 4995 transactions.

**What version of MintAPI are you using?**
latest
**What command[s] did you run / steps to reproduce?**
`rawTransactions = mint.get_transaction_data() `

**Stacktrace/error received:**
Mint sync apparently incomplete after timeout.  Data retrieved may not be current.

**What did you expect to happen?**
Expected to return all the transactions (12k)
**What actually happened?**
Only 4995 transactions were downloaded
**Additional context**
I understand that downloading all 12k transaction may not be useful, but I really want to see the trend for past 2 year at least. I am not sure what I can do to get the 2 year worth of transactions.
`rawTransactions2 =   mint.get_transaction_data(  start_date='01-01-20',  end_date='09-16-22') `
However this also returns the 4995 as the length of transactions

**Comment by burkematthew** [comment]
@noblevirk a couple things that may be at play here:

1. There is a default limit of 5000 records per call. If you expect more than that from Mint, you should pass a value through the `limit` argument. 
2. You may need to pass a date filter in to specify that you are running a custom date range. 

Let me know the results of both of those! 

Matthew

**Comment by jaksaffras** [comment]
This could be related to mint itself in addition to previous poster needing to supply a the limit filter within mintapi.get_transaction_data() call.

from the UI, Mint only exports 10,000 transactions at a time for the given date range, regardless of the 
Tranasctions->Export should be 16000+ transactions, yet the UI export only has until 8/7/2018 and 10000 rows.
9/1/2013-9/1/2020 should export 11,300 transactions, yet the UI export only returns that perfect 10000 once more.

**Comment by CalvinChanCan** [comment]
Just wanted to chip in here but there is a way to download all transactions despite the 10K limit per call. 

If you have less than 10K transactions in a single year, what you could do is provide a date filter for that year and loop through each and append it an aggregated list.

For example:

```
        all_transactions = []

        for year in range(2017, datetime.date.today().year + 1, 1):
            start_date = datetime.date(year, 1, 1)
            end_date = datetime.date(year, 12, 31)
            transaction_data = mint_client.get_transaction_data(
                limit=10000,
                date_filter=DateFilter.Options.CUSTOM,
                start_date=start_date.strftime("%m/%d/%y"),
                end_date=end_date.strftime("%m/%d/%y"),
            )
            all_transactions = all_transactions + transaction_data
```

**Comment by eyadgaran** [comment]
to chime in here a bit late - this behavior is related to pagination. the api uses the limit param to chunk the response across multiple calls. the default implementation across all endpoints is a single api call, so the max records returned is going to be the min(limit, server_imposed_max). if you inspect the responses, however, they contain the information to iterate through the next pages until there is no more data to be fetched ("pagination")

it isnt incorporated upstream yet but you can find an example of pagination in this pr: https://github.com/mintapi/mintapi/pull/482/files#diff-9c6a633063c74321fc30f1d2fee0b6fcd634569eba053daa5ab73a2c60544b7cR44

cheers!
