### ISSUE TITLE
Write Access to Split a Transaction and Set Category

### ISSUE THREAD

**Issue by ddcruver** [mintapi/mintapi#539]
While implementing a read API without a official API is impressive, I have ideas of how someone could download their information from Amazon process the categories in which the transactions could be in and then make a list of transactions to split and categorize in Mint.  

With this information you could update Mint to have more accurate spending information across services for us that use big online stores for a majority of our shopping.  Which in itself is a problem.

Does mintapi support anything write access at all?

**Comment by burkematthew** [comment]
Hi @ddcruver -

At this point, we are only focused on maintaining mintapi as a read-only tool.  I'll defer to @mrooney for final say, though.

**Comment by mrooney** [comment]
It does not currently support write activities. For better categorization, I could see a browser extension doing well at that for folks who actively use the website. I'd be more a fan of a separate project that uses mintapi as a dependency, and would be happy to support any API changes on our side to make login and requests more re-usable.
