### ISSUE TITLE
Is initialize_serverless_chrome_driver missing?

### ISSUE THREAD

**Issue by CalvinChanCan** [mintapi/mintapi#540]
Hi, I was going through the readme to setup mintapi on AWS Lambda. The readme mentioned there was a constructor for a pre-configured headless serverless chrome `initialize_serverless_chrome_driver` but I don't see this method available. Is this missing from the api?

**Comment by mrooney** [comment]
Thanks for giving it a shot! I believe this is intended simply as a sort of stub method, ie `your_custom_chrome_driver_instantiation_here()`. From the linked page in that section, you can see they add a bunch of options before doing `driver = webdriver.Chrome(chrome_options=chrome_options)`. It's just showing how to pass a custom driver. If you have any suggestions to improve the README in this section, please do send them along via PR or suggestion!
