### ISSUE TITLE
Cannot get past Sign In screen with 2.8

### ISSUE THREAD

**Issue by jcsacto** [mintapi/mintapi#547]
**Describe the bug**
I updated to 2.8 in my Dev environment and it can no longer get past the Sign in screen. 

What version of MintAPI are you using? 2.8
What command[s] did you run / steps to reproduce? 

import mintapi
import pandas as pd
import gspread
import time 
from df2gspread import df2gspread as d2g 
from oauth2client.service_account import ServiceAccountCredentials
from config import username, password

#WHEN CHROME DRIVER GETS OUT OF DATE, SIMPLY UPDATE CHROME AND UPDATE CHROME DRIVER IN THE MINTPIPELINE DIRECTOR

mint = mintapi.Mint(
    username,  # Email used to log in to Mint
    password,  # Your password used to log in to mint
    # Optional parameters
    mfa_method='soft-token',  # See MFA Methods section
                       # Can be 'sms' (default), 'email', or 'soft-token'.
                       # if mintapi detects an MFA request, it will trigger the requested method
                       # and prompt on the command line.
    mfa_input_callback=None,  # see MFA Methods section
                              # can be used with any mfa_method
                              # A callback accepting a single argument (the prompt)
                              # which returns the user-inputted 2FA code. By default
                              # the default Python `input` function is used.
    mfa_token='LSOFXXXXXXXXXXXXXXXXXXXXXXXXXXXX',   # see MFA Methods section
                      # used with mfa_method='soft-token'
                      # the token that is used to generate the totp
    intuit_account=None, # account name when multiple accounts are registered with this email.
    headless=True,  # Whether the chromedriver should work without opening a
                     # visible window (useful for server-side deployments)
                         # None will use the default account.
    session_path=r"C:\Users\Jon Crosby\Dropbox\Repos\python\mintPipeline\SessionPath", # Directory that the Chrome persistent session will be written/read from.
                       # To avoid the 2FA code being asked for multiple times, you can either set
                       # this parameter or log in by hand in Chrome under the same user this runs
                       # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
    wait_for_sync=False,  # do not wait for accounts to sync
    wait_for_sync_timeout=300,  # number of seconds to wait for sync
	use_chromedriver_on_path=False,  # True will use a system provided chromedriver binary that
	                                 # is on the PATH (instead of downloading the latest version)
  )

Stacktrace/error received:
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D535c111f-1b72-4ca8-b17e-63e0d998088a
**What did you expect to happen?**
It should get to the next screen and pass my credentials and then my MFA token through
**What actually happened?**
I got the error above
**Additional context**
Screen it stops at: 
![image](https://user-images.githubusercontent.com/31897194/194731061-bcb19b8b-5f58-457e-a3d7-cfcb80887dfa.png)

**Comment by felciano** [comment]
@jcsacto do you get a stack trace dumped out, or just an error message on the CLI?

**Comment by jcsacto** [comment]
@felciano  here is everthing I get back..including a 'backtrace'

TimeoutException                          Traceback (most recent call last)
File c:\Users\Jon Crosby\.conda\envs\mintEnv3\lib\site-packages\mintapi\api.py:195, in Mint.login_and_get_token(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, fail_if_stale, use_chromedriver_on_path, chromedriver_download_path, driver, beta)
    194 try:
--> 195     self.status_message = sign_in(
    196         email,
    197         password,
    198         self.driver,
    199         mfa_method,
    200         mfa_token,
    201         mfa_input_callback,
    202         intuit_account,
    203         wait_for_sync,
    204         wait_for_sync_timeout,
    205         fail_if_stale,
    206         imap_account,
    207         imap_password,
    208         imap_server,
    209         imap_folder,
    210         beta,
    211     )
    212 except Exception as e:

File c:\Users\Jon Crosby\.conda\envs\mintEnv3\lib\site-packages\mintapi\signIn.py:351, in sign_in(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, fail_if_stale, imap_account, imap_password, imap_server, imap_folder, beta)
    349     home_page(driver)
...
    215 self.driver.quit()
    216 self.driver = None
--> 217 raise Exception(msg) from e

Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D535c111f-1b72-4ca8-b17e-63e0d998088a



**Backtrace:** 
{
	"name": "Exception",
	"message": "Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D535c111f-1b72-4ca8-b17e-63e0d998088a",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mTimeoutException\u001b[0m                          Traceback (most recent call last)\nFile \u001b[1;32mc:\\Users\\Jon Crosby\\.conda\\envs\\mintEnv3\\lib\\site-packages\\mintapi\\api.py:195\u001b[0m, in \u001b[0;36mMint.login_and_get_token\u001b[1;34m(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, fail_if_stale, use_chromedriver_on_path, chromedriver_download_path, driver, beta)\u001b[0m\n\u001b[0;32m    194\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 195\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstatus_message \u001b[39m=\u001b[39m sign_in(\n\u001b[0;32m    196\u001b[0m         email,\n\u001b[0;32m    197\u001b[0m         password,\n\u001b[0;32m    198\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdriver,\n\u001b[0;32m    199\u001b[0m         mfa_method,\n\u001b[0;32m    200\u001b[0m         mfa_token,\n\u001b[0;32m    201\u001b[0m         mfa_input_callback,\n\u001b[0;32m    202\u001b[0m         intuit_account,\n\u001b[0;32m    203\u001b[0m         wait_for_sync,\n\u001b[0;32m    204\u001b[0m         wait_for_sync_timeout,\n\u001b[0;32m    205\u001b[0m         fail_if_stale,\n\u001b[0;32m    206\u001b[0m         imap_account,\n\u001b[0;32m    207\u001b[0m         imap_password,\n\u001b[0;32m    208\u001b[0m         imap_server,\n\u001b[0;32m    209\u001b[0m         imap_folder,\n\u001b[0;32m    210\u001b[0m         beta,\n\u001b[0;32m    211\u001b[0m     )\n\u001b[0;32m    212\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\nFile \u001b[1;32mc:\\Users\\Jon Crosby\\.conda\\envs\\mintEnv3\\lib\\site-packages\\mintapi\\signIn.py:351\u001b[0m, in \u001b[0;36msign_in\u001b[1;34m(email, password, driver, mfa_method, mfa_token, mfa_input_callback, intuit_account, wait_for_sync, wait_for_sync_timeout, fail_if_stale, imap_account, imap_password, imap_server, imap_folder, beta)\u001b[0m\n\u001b[0;32m    349\u001b[0m     home_page(driver)\n\u001b[1;32m--> 351\u001b[0m WebDriverWait(driver, \u001b[39m20\u001b[39;49m)\u001b[39m.\u001b[39;49muntil(\n\u001b[0;32m    352\u001b[0m     expected_conditions\u001b[39m.\u001b[39;49mpresence_of_element_located(\n\u001b[0;32m    353\u001b[0m         (\n\u001b[0;32m    354\u001b[0m             By\u001b[39m.\u001b[39;49mCSS_SELECTOR,\n\u001b[0;32m    355\u001b[0m             \u001b[39m\"\u001b[39;49m\u001b[39m#ius-link-use-a-different-id-known-device, #ius-userid, #ius-identifier, #ius-option-username\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[0;32m    356\u001b[0m         )\n\u001b[0;32m    357\u001b[0m     )\n\u001b[0;32m    358\u001b[0m )\n\u001b[0;32m    359\u001b[0m driver\u001b[39m.\u001b[39mimplicitly_wait(\u001b[39m0\u001b[39m)  \u001b[39m# seconds\u001b[39;00m\n\nFile \u001b[1;32mc:\\Users\\Jon Crosby\\.conda\\envs\\mintEnv3\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:90\u001b[0m, in \u001b[0;36mWebDriverWait.until\u001b[1;34m(self, method, message)\u001b[0m\n\u001b[0;32m     89\u001b[0m         \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m---> 90\u001b[0m \u001b[39mraise\u001b[39;00m TimeoutException(message, screen, stacktrace)\n\n\u001b[1;31mTimeoutException\u001b[0m: Message: \nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00931ED3+2236115]\n\tOrdinal0 [0x008C92F1+1807089]\n\tOrdinal0 [0x007D66FD+812797]\n\tOrdinal0 [0x008055DF+1005023]\n\tOrdinal0 [0x008057CB+1005515]\n\tOrdinal0 [0x00837632+1209906]\n\tOrdinal0 [0x00821AD4+1120980]\n\tOrdinal0 [0x008359E2+1202658]\n\tOrdinal0 [0x008218A6+1120422]\n\tOrdinal0 [0x007FA73D+960317]\n\tOrdinal0 [0x007FB71F+964383]\n\tGetHandleVerifier [0x00BDE7E2+2743074]\n\tGetHandleVerifier [0x00BD08D4+2685972]\n\tGetHandleVerifier [0x009C2BAA+532202]\n\tGetHandleVerifier [0x009C1990+527568]\n\tOrdinal0 [0x008D080C+1837068]\n\tOrdinal0 [0x008D4CD8+1854680]\n\tOrdinal0 [0x008D4DC5+1854917]\n\tOrdinal0 [0x008DED64+1895780]\n\tBaseThreadInitThunk [0x770BFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77A67B5E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77A67B2E+238]\n\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)\n\u001b[1;32mc:\\Users\\Jon Crosby\\Dropbox\\Repos\\python\\mintPipeline\\mintTransaction.ipynb Cell 1\u001b[0m in \u001b[0;36m<cell line: 11>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=6'>7</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mconfig\u001b[39;00m \u001b[39mimport\u001b[39;00m username, password\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=8'>9</a>\u001b[0m \u001b[39m#WHEN CHROME DRIVER GETS OUT OF DATE, SIMPLY UPDATE CHROME AND UPDATE CHROME DRIVER IN THE MINTPIPELINE DIRECTOR\u001b[39;00m\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=10'>11</a>\u001b[0m mint \u001b[39m=\u001b[39m mintapi\u001b[39m.\u001b[39;49mMint(\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=11'>12</a>\u001b[0m     username,  \u001b[39m# Email used to log in to Mint\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=12'>13</a>\u001b[0m     password,  \u001b[39m# Your password used to log in to mint\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=13'>14</a>\u001b[0m     \u001b[39m# Optional parameters\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=14'>15</a>\u001b[0m     mfa_method\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39msoft-token\u001b[39;49m\u001b[39m'\u001b[39;49m,  \u001b[39m# See MFA Methods section\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=15'>16</a>\u001b[0m                        \u001b[39m# Can be 'sms' (default), 'email', or 'soft-token'.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=16'>17</a>\u001b[0m                        \u001b[39m# if mintapi detects an MFA request, it will trigger the requested method\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=17'>18</a>\u001b[0m                        \u001b[39m# and prompt on the command line.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=18'>19</a>\u001b[0m     mfa_input_callback\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,  \u001b[39m# see MFA Methods section\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=19'>20</a>\u001b[0m                               \u001b[39m# can be used with any mfa_method\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=20'>21</a>\u001b[0m                               \u001b[39m# A callback accepting a single argument (the prompt)\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=21'>22</a>\u001b[0m                               \u001b[39m# which returns the user-inputted 2FA code. By default\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=22'>23</a>\u001b[0m                               \u001b[39m# the default Python `input` function is used.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=23'>24</a>\u001b[0m     mfa_token\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mLSOFVRCUAAPOXVYSFMZVTOO3SJJDXBKV\u001b[39;49m\u001b[39m'\u001b[39;49m,   \u001b[39m# see MFA Methods section\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=24'>25</a>\u001b[0m                       \u001b[39m# used with mfa_method='soft-token'\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m                       \u001b[39m# the token that is used to generate the totp\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m     intuit_account\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m, \u001b[39m# account name when multiple accounts are registered with this email.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=27'>28</a>\u001b[0m     headless\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,  \u001b[39m# Whether the chromedriver should work without opening a\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=28'>29</a>\u001b[0m                      \u001b[39m# visible window (useful for server-side deployments)\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=29'>30</a>\u001b[0m                          \u001b[39m# None will use the default account.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=30'>31</a>\u001b[0m     session_path\u001b[39m=\u001b[39;49m\u001b[39mr\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39mC:\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mUsers\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mJon Crosby\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mDropbox\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mRepos\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mpython\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mmintPipeline\u001b[39;49m\u001b[39m\\\u001b[39;49m\u001b[39mSessionPath\u001b[39;49m\u001b[39m\"\u001b[39;49m, \u001b[39m# Directory that the Chrome persistent session will be written/read from.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=31'>32</a>\u001b[0m                        \u001b[39m# To avoid the 2FA code being asked for multiple times, you can either set\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=32'>33</a>\u001b[0m                        \u001b[39m# this parameter or log in by hand in Chrome under the same user this runs\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=33'>34</a>\u001b[0m                        \u001b[39m# as.\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=34'>35</a>\u001b[0m     imap_account\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m, \u001b[39m# account name used to log in to your IMAP server\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=35'>36</a>\u001b[0m     imap_password\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m, \u001b[39m# account password used to log in to your IMAP server\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=36'>37</a>\u001b[0m     imap_server\u001b[39m=\u001b[39;49m\u001b[39mNone\u001b[39;49;00m,  \u001b[39m# IMAP server host name\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=37'>38</a>\u001b[0m     imap_folder\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mINBOX\u001b[39;49m\u001b[39m'\u001b[39;49m,  \u001b[39m# IMAP folder that receives MFA email\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=38'>39</a>\u001b[0m     wait_for_sync\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,  \u001b[39m# do not wait for accounts to sync\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=39'>40</a>\u001b[0m     wait_for_sync_timeout\u001b[39m=\u001b[39;49m\u001b[39m300\u001b[39;49m,  \u001b[39m# number of seconds to wait for sync\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=40'>41</a>\u001b[0m \tuse_chromedriver_on_path\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,  \u001b[39m# True will use a system provided chromedriver binary that\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=41'>42</a>\u001b[0m \t                                 \u001b[39m# is on the PATH (instead of downloading the latest version)\u001b[39;49;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/Jon%20Crosby/Dropbox/Repos/python/mintPipeline/mintTransaction.ipynb#W0sZmlsZQ%3D%3D?line=42'>43</a>\u001b[0m   )\n\nFile \u001b[1;32mc:\\Users\\Jon Crosby\\.conda\\envs\\mintEnv3\\lib\\site-packages\\mintapi\\api.py:122\u001b[0m, in \u001b[0;36mMint.__init__\u001b[1;34m(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, fail_if_stale, use_chromedriver_on_path, chromedriver_download_path, driver, beta)\u001b[0m\n\u001b[0;32m    119\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstatus_message \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m    121\u001b[0m \u001b[39mif\u001b[39;00m email \u001b[39mand\u001b[39;00m password:\n\u001b[1;32m--> 122\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogin_and_get_token(\n\u001b[0;32m    123\u001b[0m         email,\n\u001b[0;32m    124\u001b[0m         password,\n\u001b[0;32m    125\u001b[0m         mfa_method\u001b[39m=\u001b[39;49mmfa_method,\n\u001b[0;32m    126\u001b[0m         mfa_token\u001b[39m=\u001b[39;49mmfa_token,\n\u001b[0;32m    127\u001b[0m         mfa_input_callback\u001b[39m=\u001b[39;49mmfa_input_callback,\n\u001b[0;32m    128\u001b[0m         intuit_account\u001b[39m=\u001b[39;49mintuit_account,\n\u001b[0;32m    129\u001b[0m         headless\u001b[39m=\u001b[39;49mheadless,\n\u001b[0;32m    130\u001b[0m         session_path\u001b[39m=\u001b[39;49msession_path,\n\u001b[0;32m    131\u001b[0m         imap_account\u001b[39m=\u001b[39;49mimap_account,\n\u001b[0;32m    132\u001b[0m         imap_password\u001b[39m=\u001b[39;49mimap_password,\n\u001b[0;32m    133\u001b[0m         imap_server\u001b[39m=\u001b[39;49mimap_server,\n\u001b[0;32m    134\u001b[0m         imap_folder\u001b[39m=\u001b[39;49mimap_folder,\n\u001b[0;32m    135\u001b[0m         wait_for_sync\u001b[39m=\u001b[39;49mwait_for_sync,\n\u001b[0;32m    136\u001b[0m         wait_for_sync_timeout\u001b[39m=\u001b[39;49mwait_for_sync_timeout,\n\u001b[0;32m    137\u001b[0m         fail_if_stale\u001b[39m=\u001b[39;49mfail_if_stale,\n\u001b[0;32m    138\u001b[0m         use_chromedriver_on_path\u001b[39m=\u001b[39;49muse_chromedriver_on_path,\n\u001b[0;32m    139\u001b[0m         chromedriver_download_path\u001b[39m=\u001b[39;49mchromedriver_download_path,\n\u001b[0;32m    140\u001b[0m         driver\u001b[39m=\u001b[39;49mdriver,\n\u001b[0;32m    141\u001b[0m         beta\u001b[39m=\u001b[39;49mbeta,\n\u001b[0;32m    142\u001b[0m     )\n\nFile \u001b[1;32mc:\\Users\\Jon Crosby\\.conda\\envs\\mintEnv3\\lib\\site-packages\\mintapi\\api.py:217\u001b[0m, in \u001b[0;36mMint.login_and_get_token\u001b[1;34m(self, email, password, mfa_method, mfa_token, mfa_input_callback, intuit_account, headless, session_path, imap_account, imap_password, imap_server, imap_folder, wait_for_sync, wait_for_sync_timeout, fail_if_stale, use_chromedriver_on_path, chromedriver_download_path, driver, beta)\u001b[0m\n\u001b[0;32m    215\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdriver\u001b[39m.\u001b[39mquit()\n\u001b[0;32m    216\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdriver \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m--> 217\u001b[0m \u001b[39mraise\u001b[39;00m \u001b[39mException\u001b[39;00m(msg) \u001b[39mfrom\u001b[39;00m \u001b[39me\u001b[39;00m\n\n\u001b[1;31mException\u001b[0m: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D535c111f-1b72-4ca8-b17e-63e0d998088a"
}

**Comment by mrooney** [comment]
Thanks! Does using an older version like mintapi==2.7 get past the issue? I'm curious if this is an issue with newer Chrome like some folks were seeing on Discord.

**Comment by jcsacto** [comment]
I tried uninstalling and then installing 2.7 and 2.6 (pip install mintapi==2.7) but still getting the same behavior.  This is on windows where I do Dev/Testing, I am using 2.6 in a Docker container on GCP cloudrun for my production version which still seems to be working fine...if that helps.

**Comment by jcsacto** [comment]
Adding response from babbeuf on Discord regarding his work around on this issue.  

**babbeuf — Today at 9:18 AM
I had the same problem getting through the login screen. It looks like Mint changed the id tag designating the text box from "#ius-userid' or similar to '#iux-identitifier-first-unknown-identifier.' When I added that tag to the sign_in function in signIn.py, it worked.**

**Comment by mrooney** [comment]
Can you please try 2.9 from pypi and let me know if that resolves the issue? Thanks!

**Comment by jcsacto** [comment]
tested 2.9 and has resolved my issue, thanks!
