### ISSUE TITLE
Not able to signin in mintapi v2.8

### ISSUE THREAD

**Issue by ujjwalkrishna** [mintapi/mintapi#558]
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3Ddc411d93-0b38-4df7-8606-3cc53c71d265

**Comment by mrooney** [comment]
Given that this doesn't follow the bug template and there are various previous reports, I'll close this. However, if after reviewing other issues and trying the latest `main` you can still repro the issue, feel free to file an issue using the template. Thanks!

**Comment by mrooney** [comment]
I just released mintapi 2.9 to pypi, give it a shot :)
