### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [mintapi/mintapi#562]
Hi, In **mintapi**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
configargparse==1.5.3
future==0.18.2
keyring==23.2.1
mock==4.0.2
oathtool==2.3.0
pandas==1.3.5
selenium-requests==2.0.0
xmltodict==0.12.0
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **configargparse** can be changed to *>=0.9.3,<=1.5.3*.
The version constraint of dependency **future** can be changed to *>=0.12.0,<=0.18.2*.
The version constraint of dependency **keyring** can be changed to *>=0.7,<=1.1.2*.
The version constraint of dependency **keyring** can be changed to *>=2.1.1,<=23.6.0*.
The version constraint of dependency **pandas** can be changed to *>=0.20.0,<=0.24.2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the configargparse</summary>
 <pre>configargparse.ArgumentParser
configargparse.ArgumentParser.parse_args
</pre>
</details>
<details><summary>The calling methods from the future</summary>
 <pre>datetime.datetime.strptime
email.header.make_header
datetime.datetime.fromtimestamp
email.header.decode_header
email.message_from_bytes
datetime.datetime.now
</pre>
</details>
<details><summary>The calling methods from the keyring</summary>
 <pre>keyring.get_password
keyring.set_password
</pre>
</details>
<details><summary>The calling methods from the pandas</summary>
 <pre>json.dumps
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>self.__first_of_this_month
atexit.register
time.sleep
open
ValueError
imaplib.IMAP4_SSL.logout
seleniumrequests.Chrome.find_element
logging.getLogger.exception
account_selection_page
driver.current_url.startswith
mintapi.filters.SearchFilter
json.dumps
self.__find_endpoint
driver.find_element.is_displayed
float
mfa_page
os.path.expanduser
datetime.datetime.strptime
mintapi.trends.ReportView
get_email_code
self.driver.execute_script
imaplib.IMAP4_SSL.login
bypass_verified_user_page
handle_password
mintapi.api.Mint.get_bills
email.message_from_bytes
self._flatten_utilization
str
next
Mint.get_account_data
self.date_filter.to_dict
self.__x_months_ago
os.path.exists
selenium.webdriver.support.expected_conditions.url_contains
self.login_and_get_token
input
msg.walk.next.get_payload.decode
set
subprocess.check_output
re.compile.search
io.BytesIO
mintapi.api.Mint.get_budget_data
dateutil.relativedelta.relativedelta
mintapi.filters.DateFilter
Mint
imaplib.IMAP4_SSL.select
email.header.make_header
email.header.decode_header
oathtool.generate_otp
configargparse.ArgumentParser.add_argument
setuptools.setup
months.relativedelta.self.__first_of_this_month.replace
logging.getLogger.error
data.split
driver.WebDriverWait.until
selenium.webdriver.support.ui.WebDriverWait
self.report_view.to_dict
imaplib.IMAP4_SSL.store
mintapi.api.Mint.get_trend_data
self._get_credit_reports
requests.get
email.message_from_bytes.walk
cu_month.datetime.strptime.replace
configargparse.ArgumentParser
self.get_credit_accounts
imaplib.IMAP4_SSL.search
keyring.get_password
self.status_message.split
subprocess.check_output.decode
self.status_message.split.strip
convert_mmddyy_to_datetime
output_data
logging.getLogger.critical
get_stable_chrome_driver
self.get_credit_report_data
zipfile.ZipFile
self._get_api_key_header.constants.MINT_ROOT_URL.format.self.get.json
mintapi.api.Mint.get_category_data
utilization.append
parse_arguments
handle_different_page_username_password
MFAMethodNotAvailableError
self.__append_filter.append
handle_other_mfa
self.post.json
logging.getLogger.debug
handle_email_by_imap
imaplib.IMAP4_SSL
datetime.datetime.fromtimestamp
zipfile.ZipFile.extractall
sum
selenium.webdriver.support.expected_conditions.presence_of_element_located
mintapi.api.Mint.get_net_worth_data
selenium.webdriver.ChromeOptions.add_argument
os.getcwd
self.get_account_data
self.__append_filter
mintapi.filters.DateFilter.Options
self.__build_payload.to_dict
self.driver.get
cu_month.datetime.strptime.replace.strftime
version_pattern.match.groupdict
fh.read
mintapi.api.Mint.get_credit_report_data
cu_month.datetime.strptime.replace.today
match_filter.to_dict
isinstance
print
pandas.json_normalize
os.chmod
wait_for_sync_timeout.driver.WebDriverWait.until
Mint.get_credit_report
get_latest_chrome_driver_version
list
RuntimeError
list.get
bypass_passwordless_login_page
mintapi.api.Mint
self.get_data
mintapi.api.Mint.get_account_data
seleniumrequests.Chrome.execute_script
logging.getLogger.warning
any
Mint.initiate_account_refresh
mintapi.signIn._create_web_driver_at_mint_com
utilization.extend
os.remove
password_page
f.write
seleniumrequests.Chrome
format_filename
mintapi.api.Mint.get_attention
logging.getLogger
int
logging.getLogger.setLevel
handle_same_page_username_password
type.lower
selenium.webdriver.common.by.By.ID.driver.find_element.send_keys
re.compile
datetime.date.today.replace
mfa_selection_page
hasattr
mintapi.trends.ReportView.Options
msg.walk.next.get_payload
self.get
submit_mfa_code
Mint.get_budgets
selenium.webdriver.common.by.By.CSS_SELECTOR.driver.find_element.click
search_mfa_method
self._load_mint_credit_url
self._get_api_key_header
self.__get_mint_endpoint
header.update
username_element.click
self.driver.quit
selenium.common.exceptions.ElementNotVisibleException
format.format
list.keys
driver.find_element.click
self.post
os.path.dirname
SELECT_CSS_SELECTORS_LABEL.mfa_result.By.CSS_SELECTOR.driver.find_element.click
re.search
get_chrome_driver_major_version_from_executable
data.json_normalize.to_csv
selenium.webdriver.support.expected_conditions.visibility_of_element_located
driver.find_element.find_element
imaplib.IMAP4_SSL.expunge
getpass.getpass
get_chrome_driver_url
logging.getLogger.info
selenium.webdriver.ChromeOptions
handle_wait_for_sync
email.utils.parsedate_tz
configargparse.ArgumentParser.parse_args
re.compile.match
format
self.__build_search_clauses
re.search.group
self.__post_mint_endpoint
credit_header.limit.constants.MINT_CREDIT_URL.format.self.get.json
i.pop
seleniumrequests.Chrome.implicitly_wait
dict
Mint.get_credit_score
imaplib.IMAP4_SSL.fetch
email.utils.mktime_tz
mintapi.cli.main
filter
self.search_filters.to_dict
mintapi.api.Mint.get_investment_data
handle_login_failures
datetime.datetime.now
self.get_credit_utilization
input.mfa_input_callback
self.driver.request
keyring.set_password
MintException
driver.find_element.send_keys
handle_soft_token
CHROME_DRIVER_DOWNLOAD_PATH.format
driver.find_element.clear
mintapi.api.Mint.get_transaction_data
self.__build_payload
request
sys.exit
mintapi.signIn.get_email_code
selenium.webdriver.common.by.By.CSS_SELECTOR.driver.find_element.send_keys
row.replace
home_page
selenium.webdriver.common.by.By.LINK_TEXT.driver.find_element.click
Mint.get_net_worth
driver.WebDriverWait.until.get_attribute
selenium.webdriver.common.by.By.ID.driver.find_element.click
json.dump
mintapi.signIn.sign_in
CHROME_ZIP_TYPES.get
self._get_credit_details
mintapi.api.Mint.get_credit_score_data
SPAN_CSS_SELECTORS_LABEL.method.By.CSS_SELECTOR.driver.find_element.text.lower
range
dataclasses.field
self._process_utilization
os.path.join
credit_header.constants.MINT_CREDIT_URL.url.format.self.get.json
self.get_credit_inquiries
selenium.webdriver.common.by.By.CSS_SELECTOR.driver.find_element.submit
Exception
seleniumrequests.Chrome.get
user_selection_page
set_mfa_method
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by mrooney** [comment]
Thanks! I would consider it a best practice to have specific pinned versions, so that everyone gets the same thing out of the box and a bunch of variables are eliminated. However, if there are any that you think should be updated, I'm happy to have a PR updating them!
