### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by pdeangelo** [mintapi/mintapi#606]
**Describe the bug**
Recently started getting this error message

What version of MintAPI are you using?
I believe it is 2.7 found this in mintapi-script.py

What command[s] did you run / steps to reproduce?
Stacktrace/error received:
raceback (most recent call last):
  File "C:\Users\pdean\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\api.py", line 195, in login_and_get_token
    self.status_message = sign_in(
  File "C:\Users\pdean\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\signIn.py", line 351, in sign_in
    WebDriverWait(driver, 20).until(
  File "C:\Users\pdean\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by rohandvora** [comment]
I am getting the same issue since a few weeks now. Mint API version: 2.14, chrome version 116.0.

**Comment by azhumabaev** [comment]
Same exception, almost 2 weeks. mintapi: 2.14, chrome: 116.0.

**Comment by timdau** [comment]
In the docker container, I am executing `rm -rf ~/.mintapi` prior to running, and it seems to work.

**Comment by codemang** [comment]
I'm still getting this error, any suggestions?

**Comment by codemang** [comment]
Upgrading to mintapi 2.15 fixed it for me.

**Comment by mrooney** [comment]
> Upgrading to mintapi 2.15 fixed it for me.

Thanks for the confirmation!
