### ISSUE TITLE
Chromedriver for Chrome 116 issue

### ISSUE THREAD

**Issue by pdeangelo** [mintapi/mintapi#610]
Hi,

I upgraded to Chrome 116 and now I am getting this error:
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.97 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

I downloaded the new chromedriver from this url https://googlechromelabs.github.io/chrome-for-testing/ but I still get the same error, has anyone else experienced this?

Thank you,

Paul

**Comment by rohandvora** [comment]
I'm getting the same error since the last few days.

**Comment by CalvinChanCan** [comment]
I'm getting the same error but found a temporary solution.

1. Download chromedriver 116. You can verify the version with `chromedriver --version` which should output ChromeDriver 116.0.5845.96 
2. In your mint constructor,  set `use_chromedriver_on_path=True`. If this is not set, then your chromedriver will be overwritten with chromedriver 114

**Comment by jraymond4321** [comment]
I'm getting the same issue.  I've tried setting "use_chromedriver_on_path=True" on both the Browser.py and Signin.py files.  I'm downloading chromedriver.exe (ver 116) to my working directory, but it is still pulling the 114 version down and overwriting the 116 version.

**Comment by CalvinChanCan** [comment]
@jraymond4321 , can you share which version of mintapi you're using? Its strange that its still overwriting with `use_chromedriver_on_path=True` since mintapi should be looking for the chromedrive instead of downloading a new one.

```
      mint = Mint(
          email=email,
          password=password,
          mfa_method="soft-token",
          mfa_token=mfa_token,
          use_rest_client=True,
          use_chromedriver_on_path=True,
          headless=True,
          wait_for_sync=False,
      )
```

**Comment by jraymond4321** [comment]
@CalvinChanCan  I'm running 2.14 also (see below).  I'm not a python expert, so I'm not sure what you mean by constructor.

C:\Python311\Lib\site-packages\mintapi>pip install mintapi
Requirement already satisfied: mintapi in c:\python311\lib\site-packages (2.14)

Thanks.

**Comment by CalvinChanCan** [comment]
@jraymond4321, thanks for confirming its mint 2.14. Sorry for the confusion. By constructor, I meant the arguments we're using to instantiate the Mint object. In this case, I wanted to show the example that `use_chromedriver_on_path` is being set to true when using `Mint(...)`. Can you share your code on how're you're setting `use_chromedriver_on_path=True` on both the Browser.py and Signin.py files?

 mint = Mint(
          email=email,
          password=password,
          mfa_method="soft-token",
          mfa_token=mfa_token,
          use_rest_client=True,
          use_chromedriver_on_path=True, <---
          headless=True,
          wait_for_sync=False,
      )

**Comment by jraymond4321** [comment]
Hi @CalvinChanCan , thanks for your help.  I made a mistake, it was working.  I had not saved the batch file with the passing the parameter to use the Chromedriver in path.  Once I saved it, it ran fine.
