### ISSUE TITLE
Automatically detecting categories

### ISSUE THREAD

**Issue by matthieuheitz** [mintapi/mintapi#613]
Is there a way to have access to the Mint function that classifies transactions into categories?
Like when transactions are taken from your bank account, it automatically finds the category and generally does a pretty good job at it.
Since I'm batch uploading transactions, but I don't have categories, I was wondering if there would be away to access that classifier.
Thanks!

**Comment by CalvinChanCan** [comment]
Unfortunately, mint does not expose the function on how they're classify transactions to categories.

**Comment by matthieuheitz** [comment]
Okay thanks!
