### ISSUE TITLE
Add support for exporting accounts to CSV

### ISSUE THREAD

**Issue by felciano** [mintapi/mintapi#88]
When trying to export account details into an Excel-compatible CSV format I get a ValueError

```
$ mintapi $MINTUSERNAME --extended-accounts --include-investment -f account-details.csv
Traceback (most recent call last):
  ... details omitted ...
    raise ValueError('file type must be json for non-transaction data')
ValueError: file type must be json for non-transaction data
```
I though this used to work and it isn't clear to me why it wouldn't. Can someone confirm? 

Workaround is to install something like https://csvkit.readthedocs.io/, exporting a json version, and then using `in2csv`, but this seems like it would be nice parsimonious functionality to have built in.

**Comment by mrooney** [comment]
It doesn't look like this ever would have worked, I can't recall any time that a format was removed from https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L750. It looks like we support exporting transactions to csv, but not accounts. I would definitely welcome a PR that abstracts some of the duplicated logic there and supports CSV+JSON for both.

**Comment by felciano** [comment]
So it looks like the current CSV functionality is just downloading Mint's CSV as is. Since you are using pandas for the json data with extended transactions, it should be straightforward to [convert to CSV](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html). 

Can you clarify what CSV compatibility behavior you'd like? This is more of a design question: even if the currently generated CSVs (assuming we use the above pandas function) product results that are identical, Mint CSV export behavior could change such that this no longer holds. So what is the API contract you want to make?

1. Same as what you get from Mint by hand.
2. CSV version of what you get from JSON functions.
3. Both / developer choice, e.g. by add a new function and command line option that produces a CSV dialect guaranteed to match the JSON version.

I sort of like the power of #3 but I'm not sure how on the command line you'd specify which CSV dialect you want.

**Comment by mrooney** [comment]
I think it makes sense, for consistency to be the CSV version of what you get from JSON functions, which I believe is what we do for transaction data: https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L744 (just call to_csv). So my suggestion would be to just abstract that logic into a function that dates data and the format and handles those options. If that won't handle your use-case though, we can figure out something better!

**Comment by felciano** [comment]
Not sure that's true. If you request regular / non-extended transactions, it looks like the source of truth is the CSV data from Mint, which is converted to JSON on the fly (https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L413), generating the JSON field names by parsing the CSV header and doing some string normalization. 

The extended transactions appears instead to start from JSON data. I'm happy to contribute a converter to CSV, but because of the above I expect it will be tricky to abstract out the capabilities since these two options use different data model starting points.

**Comment by felciano** [comment]
@mrooney any further thoughts on your preferred design approach here, given that regular and extended transactions currently appear to have different "source of truth" starting points for their data?

**Comment by mrooney** [comment]
Yes, I see what you mean, and apologies for the delay. I didn't realize the one is a pandas data frame and the other is plain JSON (generally, a list)

My current thought would be to make a helper export function that can take either a pandas data frame OR a python list. 

[
  {
    "closeDateInDate": "datetime.datetime(2017, 4, 9, 22, 41, 38)", 
    "lastUpdatedInDate": "datetime.datetime(2017, 4, 9, 22, 41, 41)", 
  }, 
  {
    "closeDateInDate": "datetime.datetime(2017, 4, 9, 22, 41, 38)", 
    "lastUpdatedInDate": "datetime.datetime(2017, 4, 9, 22, 41, 41)",
  }
]

So, if we receive something like this, we iterate over all entries to make a complete list of column names (closeDateInDate and lastUpdatedInDate) in this quick example, then iterate over each and populate CSV data based on key name. This way, if one item is missing a key, it can doesn't matter and they can all be exported to CSVs. Does that make any sense? Then, the whole if/else starting with `if options.transactions or options.extended_transactions:` can use this method.

**Comment by burkematthew** [comment]
So from what I can tell, the only thing standing in the way of outputting accounts to CSV from the immediate response is an addresses object that needs a little flattening.  Other than that, there does not seem to be anything standing in the way of just converting the JSON to CSV.

**Comment by burkematthew** [comment]
@mrooney thoughts on the above comment?

**Comment by mrooney** [comment]
> @mrooney thoughts on the above comment?

Yeah, sounds great to me! I certainly welcome any fixes to that. :)

**Comment by burkematthew** [comment]
@felciano @mrooney @jaron-l after looking at this, I realized that there is one field `possibleLinkAccounts`, that could potentially be an array.  However, I do not have any data populated in this array on my various accounts.  I wanted to see if anyone else had data in that array?

**Comment by mrooney** [comment]
> @felciano @mrooney @jaron-l after looking at this, I realized that there is one field `possibleLinkAccounts`, that could potentially be an array. However, I do not have any data populated in this array on my various accounts. I wanted to see if anyone else had data in that array?

If it isn't possible to handle without seeing example data, you could just catch that scenario with an error message to submit a bug report with an example of the data. That way, if it is a common thing, we'll get a report with some example data to use.

**Comment by burkematthew** [comment]
@mrooney thinking about it, I made this comment before making the realization about the `providers` endpoint.  I probably want to postpone flattening to CSV until we move towards implementing that new endpoint.

**Comment by burkematthew** [comment]
@mrooney that being said, for v1, I think we could just add the error saying account details are not compatible with CSV instead of after fetching the data. Then for v2, when we work on exporting account data to CSV, we can remove that requirement.

**Comment by mrooney** [comment]
@burkematthew sounds good to me! :) 👍

**Comment by burkematthew** [comment]
@felciano can you see if the latest on main meets your needs for exporting accounts to CSV?  Keep in mind that `--extended-accounts` is no longer necessary, so you can just specify `--accounts`.
