### ISSUE TITLE
choose output as csv or json when printing output to stdout

### ISSUE THREAD

**Issue by sken77** [mintapi/mintapi#89]
when transaction output is sent to `stdout` allow to be able to choose between csv and json

**Comment by mrooney** [comment]
Seems reasonable, PRs welcome!

**Comment by bradmalloy** [comment]
I'll take a crack at this

**Comment by burkematthew** [comment]
@jaron-l I know you had some thoughts about this when discussing #256 .  What are your thoughts on this?

**Comment by jaron-l** [comment]
> @jaron-l I know you had some thoughts about this when discussing #256 . What are your thoughts on this?

My only concern is to avoid breaking the current workflow. So since json is the default, csv could be a flag to change the stdout.

**Comment by burkematthew** [comment]
@jaron-l yes I was thinking that it could be a new option of --csv or something like that to indicate we want to format as CSV for stdout.

**Comment by burkematthew** [comment]
@sken77 when thinking of output as CSV, do you mean a true comma-separate list or a pandas data frame?

**Comment by burkematthew** [comment]
Hi @sken77 just following up here.

**Comment by burkematthew** [comment]
Hi @sken77 just following up here.
